# This file is auto-generated by scripts/generate_shared_models.py.
# Do not edit manually.

from pydantic import BaseModel, Field

class AnkiCard(BaseModel):
    id: str = ...
    user_id: str = ...
    deck_id: str | None = Field(default=None, description='Deck/group identifier for organizing cards.')
    source_lesson_id: str | None = Field(default=None, description='Optional originating lesson identifier.')
    front_text: str = ...
    back_text: str = ...
    status: str = Field(default='new', description='Simplified learning stage for scheduling.')
    ease_factor: float = Field(default=2.5, description='Ease multiplier used to grow or shrink intervals.', ge=1.3, le=3)
    interval_days: int = Field(default=0, description='Current review interval in days.', ge=0)
    repetitions: int = Field(default=0, description='Count of successful reviews.', ge=0)
    lapses: int = Field(default=0, description='Count of failed reviews after learning.', ge=0)
    due_at: str | None = Field(default=None, description='Next scheduled review time (ISO 8601).')
    last_reviewed_at: str | None = Field(default=None, description='Most recent review time (ISO 8601).')
    is_suspended: bool = Field(default=False, description='Whether this card is temporarily excluded from reviews.')
    tags: list[str] = Field(default_factory=list)
    created_at: str = ...
    updated_at: str = ...
    created_by: str | None = Field(default=None, description='User identifier that created this record.')
    updated_by: str | None = Field(default=None, description='User identifier that last updated this record.')
    created_time: str | None = Field(default=None, description='Record creation timestamp (ISO 8601).')
    updated_time: str | None = Field(default=None, description='Record update timestamp (ISO 8601).')

class AnkiDeck(BaseModel):
    id: str = ...
    user_id: str = ...
    name: str = ...
    description: str | None = Field(default=None, description='Optional deck description.')
    is_archived: bool = Field(default=False, description='Whether the deck is archived.')
    new_cards_per_day: int = Field(default=20, description='Daily limit for new cards from this deck.', ge=0)
    review_cards_per_day: int = Field(default=200, description='Daily limit for review cards from this deck.', ge=0)
    card_count: int = Field(default=0, description='Total number of cards in the deck.', ge=0)
    card_ids: list[str] | None = Field(default=None, description='Optional card id list when preloaded; null means not loaded.')
    tags: list[str] = Field(default_factory=list)
    created_at: str = ...
    updated_at: str = ...
    created_by: str | None = Field(default=None, description='User identifier that created this record.')
    updated_by: str | None = Field(default=None, description='User identifier that last updated this record.')
    created_time: str | None = Field(default=None, description='Record creation timestamp (ISO 8601).')
    updated_time: str | None = Field(default=None, description='Record update timestamp (ISO 8601).')

class AnkiReviewLog(BaseModel):
    id: str = ...
    user_id: str = ...
    card_id: str = ...
    deck_id: str | None = Field(default=None, description='Deck context at review time, if any.')
    rating: str = ...
    elapsed_ms: int = Field(default=0, description='Time spent before answering, in milliseconds.', ge=0)
    interval_before_days: int = Field(default=0, description='Card interval before this review, in days.', ge=0)
    interval_after_days: int = Field(default=0, description='Card interval after this review, in days.', ge=0)
    ease_factor_before: float = Field(default=2.5, description='Ease factor before this review.', ge=1.3, le=3)
    ease_factor_after: float = Field(default=2.5, description='Ease factor after this review.', ge=1.3, le=3)
    reviewed_at: str = ...

class ReviewSession(BaseModel):
    id: str = ...
    user_id: str = ...
    deck_id: str | None = Field(default=None, description='Optional deck filter used to generate this session.')
    target_duration_minutes: int = Field(default=10, description='Requested study duration for this session.', ge=1)
    status: str = Field(default='planned', description='Session lifecycle state.')
    selected_card_ids: list[str] = Field(default_factory=list)
    reviewed_count: int = Field(default=0, description='How many selected cards were reviewed in this session.', ge=0)
    started_at: str | None = Field(default=None, description='When the session started (ISO 8601).')
    completed_at: str | None = Field(default=None, description='When the session was completed or abandoned (ISO 8601).')
    created_at: str = ...
    updated_at: str = ...
    created_by: str | None = Field(default=None, description='User identifier that created this record.')
    updated_by: str | None = Field(default=None, description='User identifier that last updated this record.')
    created_time: str | None = Field(default=None, description='Record creation timestamp (ISO 8601).')
    updated_time: str | None = Field(default=None, description='Record update timestamp (ISO 8601).')
