# This file is auto-generated by scripts/generate_shared_models.py.
# Do not edit manually.

from pydantic import BaseModel, Field

class Assessment(BaseModel):
    id: str = ...
    title: str = ...
    description: str | None = Field(default=None, description='Assessment description and submission instructions.')
    type: str = ...
    expected_time_minutes: int = ...
    is_published: bool = Field(default=False, description='Publishing state.')
    tags: list[str] = Field(default_factory=list)
    created_by: str | None = Field(default=None, description='User identifier that created this record.')
    updated_by: str | None = Field(default=None, description='User identifier that last updated this record.')
    created_time: str | None = Field(default=None, description='Record creation timestamp (ISO 8601).')
    updated_time: str | None = Field(default=None, description='Record update timestamp (ISO 8601).')

class Assignment(BaseModel):
    id: str = ...
    assessment_id: str = ...
    learner_id: str = ...
    title: str = ...
    description: str | None = Field(default=None, description='Assignment-specific instructions.')
    deadline: str = ...
    status: str = Field(default='assigned', description='Assignment lifecycle status.')
    assigned_at: str = ...
    submitted_at: str | None = Field(default=None, description='Submission timestamp (ISO 8601).')
    grade: float | None = Field(default=None, description='Numeric grade in range 0-100.', ge=0, le=100)
    feedback: str | None = Field(default=None, description='Evaluator feedback for the learner.')
    created_by: str | None = Field(default=None, description='User identifier that created this record.')
    updated_by: str | None = Field(default=None, description='User identifier that last updated this record.')
    created_time: str | None = Field(default=None, description='Record creation timestamp (ISO 8601).')
    updated_time: str | None = Field(default=None, description='Record update timestamp (ISO 8601).')

class Lesson(BaseModel):
    id: str = ...
    title: str = ...
    description: str | None = Field(default=None, description='Short lesson description.')
    duration_minutes: int | None = Field(default=None, description='Estimated duration in minutes.', ge=1)
    is_published: bool = Field(default=False, description='Publishing state.')
    tags: list[str] = Field(default_factory=list)
    created_by: str | None = Field(default=None, description='User identifier that created this record.')
    updated_by: str | None = Field(default=None, description='User identifier that last updated this record.')
    created_time: str | None = Field(default=None, description='Record creation timestamp (ISO 8601).')
    updated_time: str | None = Field(default=None, description='Record update timestamp (ISO 8601).')

class Skill(BaseModel):
    id: str = ...
    title: str = ...
    description: str | None = Field(default=None, description='Short skill description.')
    difficulty: str = Field(default='beginner', description='Relative skill difficulty level.')
    is_published: bool = Field(default=False, description='Publishing state.')
    tags: list[str] = Field(default_factory=list)
    created_by: str | None = Field(default=None, description='User identifier that created this record.')
    updated_by: str | None = Field(default=None, description='User identifier that last updated this record.')
    created_time: str | None = Field(default=None, description='Record creation timestamp (ISO 8601).')
    updated_time: str | None = Field(default=None, description='Record update timestamp (ISO 8601).')

class SkillLesson(BaseModel):
    id: str = ...
    skill_id: str = ...
    lesson_id: str = ...
    order_index: int = ...
    is_required: bool = Field(default=True, description='Whether the lesson must be completed to acquire the skill.')
    created_at: str | None = Field(default=None, description='Creation timestamp (ISO 8601).')
    created_by: str | None = Field(default=None, description='User identifier that created this record.')
    updated_by: str | None = Field(default=None, description='User identifier that last updated this record.')
    created_time: str | None = Field(default=None, description='Record creation timestamp (ISO 8601).')
    updated_time: str | None = Field(default=None, description='Record update timestamp (ISO 8601).')

class StudentPerformance(BaseModel):
    id: str = ...
    learner_id: str = ...
    skill_id: str = ...
    latest_history_id: str | None = Field(default=None, description='Most recent performance history entry identifier.')
    current_score: float = ...
    level_framework: str | None = Field(default=None, description='Optional proficiency framework identifier (for example cefr).')
    level_value: str | None = Field(default=None, description='Optional level value within the selected framework (for example B2).')
    trend: str = Field(default='stable', description='Short-term trend based on recent history.')
    measured_at: str = ...
    updated_at: str = ...
    created_by: str | None = Field(default=None, description='User identifier that created this record.')
    updated_by: str | None = Field(default=None, description='User identifier that last updated this record.')
    created_time: str | None = Field(default=None, description='Record creation timestamp (ISO 8601).')
    updated_time: str | None = Field(default=None, description='Record update timestamp (ISO 8601).')

class StudentPerformanceSnapshot(BaseModel):
    id: str = ...
    student_performance_id: str | None = Field(default=None, description='Referenced student performance rollup identifier, if available.')
    learner_id: str = ...
    skill_id: str = ...
    score: float = ...
    level_framework: str | None = Field(default=None, description='Optional proficiency framework identifier at this snapshot (for example cefr).')
    level_value: str | None = Field(default=None, description='Optional level value within the selected framework at this snapshot (for example B2).')
    recorded_at: str = ...
    source: str = Field(default='system', description='Source of this measurement.')
    notes: str | None = Field(default=None, description='Optional notes about the snapshot.')
    created_by: str | None = Field(default=None, description='User identifier that created this snapshot.')
    created_time: str | None = Field(default=None, description='Snapshot creation timestamp (ISO 8601).')

class StudentPerformanceTimeline(BaseModel):
    id: str = ...
    learner_id: str = ...
    skill_id: str | None = Field(default=None, description='Optional skill filter for this timeline.')
    from_time: str | None = Field(default=None, description='Inclusive lower bound of the timeline range (ISO 8601).')
    to_time: str | None = Field(default=None, description='Inclusive upper bound of the timeline range (ISO 8601).')
    snapshots: list[dict[str, object]] = Field(default_factory=list)
    performance_trends: list[dict[str, object]] = Field(default_factory=list)
    generated_at: str = ...
