# This file is auto-generated by scripts/generate_shared_models.py.
# Do not edit manually.

from pydantic import BaseModel, Field

class Lesson(BaseModel):
    id: str = ...
    title: str = ...
    description: str | None = Field(default=None, description='Short lesson description.')
    duration_minutes: int | None = Field(default=None, description='Estimated duration in minutes.', ge=1)
    is_published: bool = Field(default=False, description='Publishing state.')
    tags: list[str] = Field(default_factory=list)
