// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GeneratedContent struct {
	ID         int64              `json:"id"`
	Topic      string             `json:"topic"`
	Audience   string             `json:"audience"`
	Difficulty string             `json:"difficulty"`
	Language   string             `json:"language"`
	Lesson     []byte             `json:"lesson"`
	Skill      []byte             `json:"skill"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type PromptCacheEntry struct {
	CacheKey  string             `json:"cache_key"`
	Response  []byte             `json:"response"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}
