// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package store

import (
	"context"
)

const createGeneratedContent = `-- name: CreateGeneratedContent :one
INSERT INTO generated_contents (topic, audience, difficulty, language, lesson, skill)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, topic, audience, difficulty, language, lesson, skill, created_at
`

type CreateGeneratedContentParams struct {
	Topic      string `json:"topic"`
	Audience   string `json:"audience"`
	Difficulty string `json:"difficulty"`
	Language   string `json:"language"`
	Lesson     []byte `json:"lesson"`
	Skill      []byte `json:"skill"`
}

func (q *Queries) CreateGeneratedContent(ctx context.Context, arg CreateGeneratedContentParams) (GeneratedContent, error) {
	row := q.db.QueryRow(ctx, createGeneratedContent,
		arg.Topic,
		arg.Audience,
		arg.Difficulty,
		arg.Language,
		arg.Lesson,
		arg.Skill,
	)
	var i GeneratedContent
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.Audience,
		&i.Difficulty,
		&i.Language,
		&i.Lesson,
		&i.Skill,
		&i.CreatedAt,
	)
	return i, err
}

const getGeneratedContentByID = `-- name: GetGeneratedContentByID :one
SELECT id, topic, audience, difficulty, language, lesson, skill, created_at
FROM generated_contents
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetGeneratedContentByID(ctx context.Context, id int64) (GeneratedContent, error) {
	row := q.db.QueryRow(ctx, getGeneratedContentByID, id)
	var i GeneratedContent
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.Audience,
		&i.Difficulty,
		&i.Language,
		&i.Lesson,
		&i.Skill,
		&i.CreatedAt,
	)
	return i, err
}

const initGeneratedContentsCreatedAtIndex = `-- name: InitGeneratedContentsCreatedAtIndex :exec
CREATE INDEX IF NOT EXISTS idx_generated_contents_created_at ON generated_contents (created_at DESC)
`

func (q *Queries) InitGeneratedContentsCreatedAtIndex(ctx context.Context) error {
	_, err := q.db.Exec(ctx, initGeneratedContentsCreatedAtIndex)
	return err
}

const initGeneratedContentsTable = `-- name: InitGeneratedContentsTable :exec
CREATE TABLE IF NOT EXISTS generated_contents (
    id BIGSERIAL PRIMARY KEY,
    topic TEXT NOT NULL,
    audience TEXT NOT NULL,
    difficulty TEXT NOT NULL,
    language TEXT NOT NULL,
    lesson JSONB NOT NULL,
    skill JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
`

func (q *Queries) InitGeneratedContentsTable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, initGeneratedContentsTable)
	return err
}

const initGeneratedContentsTopicIndex = `-- name: InitGeneratedContentsTopicIndex :exec
CREATE INDEX IF NOT EXISTS idx_generated_contents_topic ON generated_contents (topic)
`

func (q *Queries) InitGeneratedContentsTopicIndex(ctx context.Context) error {
	_, err := q.db.Exec(ctx, initGeneratedContentsTopicIndex)
	return err
}

const listGeneratedContents = `-- name: ListGeneratedContents :many
SELECT id, topic, audience, difficulty, language, lesson, skill, created_at
FROM generated_contents
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListGeneratedContents(ctx context.Context, limit int32) ([]GeneratedContent, error) {
	rows, err := q.db.Query(ctx, listGeneratedContents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeneratedContent
	for rows.Next() {
		var i GeneratedContent
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Audience,
			&i.Difficulty,
			&i.Language,
			&i.Lesson,
			&i.Skill,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
