// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package store

import (
	"context"
)

type Querier interface {
	CreateGeneratedContent(ctx context.Context, arg CreateGeneratedContentParams) (GeneratedContent, error)
	GetGeneratedContentByID(ctx context.Context, id int64) (GeneratedContent, error)
	InitGeneratedContentsCreatedAtIndex(ctx context.Context) error
	InitGeneratedContentsTable(ctx context.Context) error
	InitGeneratedContentsTopicIndex(ctx context.Context) error
	ListGeneratedContents(ctx context.Context, limit int32) ([]GeneratedContent, error)
}

var _ Querier = (*Queries)(nil)
