// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package store

import (
	"context"
)

const createGeneratedContent = `-- name: CreateGeneratedContent :one
INSERT INTO generated_contents (topic, audience, difficulty, language, lesson, skill)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, topic, audience, difficulty, language, lesson, skill, created_at
`

type CreateGeneratedContentParams struct {
	Topic      string `json:"topic"`
	Audience   string `json:"audience"`
	Difficulty string `json:"difficulty"`
	Language   string `json:"language"`
	Lesson     []byte `json:"lesson"`
	Skill      []byte `json:"skill"`
}

func (q *Queries) CreateGeneratedContent(ctx context.Context, arg CreateGeneratedContentParams) (GeneratedContent, error) {
	row := q.db.QueryRow(ctx, createGeneratedContent,
		arg.Topic,
		arg.Audience,
		arg.Difficulty,
		arg.Language,
		arg.Lesson,
		arg.Skill,
	)
	var i GeneratedContent
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.Audience,
		&i.Difficulty,
		&i.Language,
		&i.Lesson,
		&i.Skill,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredPromptCacheEntries = `-- name: DeleteExpiredPromptCacheEntries :exec
DELETE FROM prompt_cache_entries
WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredPromptCacheEntries(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPromptCacheEntries)
	return err
}

const getGeneratedContentByID = `-- name: GetGeneratedContentByID :one
SELECT id, topic, audience, difficulty, language, lesson, skill, created_at
FROM generated_contents
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetGeneratedContentByID(ctx context.Context, id int64) (GeneratedContent, error) {
	row := q.db.QueryRow(ctx, getGeneratedContentByID, id)
	var i GeneratedContent
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.Audience,
		&i.Difficulty,
		&i.Language,
		&i.Lesson,
		&i.Skill,
		&i.CreatedAt,
	)
	return i, err
}

const getPromptCacheEntry = `-- name: GetPromptCacheEntry :one
SELECT cache_key, response, created_at, expires_at
FROM prompt_cache_entries
WHERE cache_key = $1
  AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetPromptCacheEntry(ctx context.Context, cacheKey string) (PromptCacheEntry, error) {
	row := q.db.QueryRow(ctx, getPromptCacheEntry, cacheKey)
	var i PromptCacheEntry
	err := row.Scan(
		&i.CacheKey,
		&i.Response,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const initGeneratedContentsCreatedAtIndex = `-- name: InitGeneratedContentsCreatedAtIndex :exec
CREATE INDEX IF NOT EXISTS idx_generated_contents_created_at ON generated_contents (created_at DESC)
`

func (q *Queries) InitGeneratedContentsCreatedAtIndex(ctx context.Context) error {
	_, err := q.db.Exec(ctx, initGeneratedContentsCreatedAtIndex)
	return err
}

const initGeneratedContentsTable = `-- name: InitGeneratedContentsTable :exec
CREATE TABLE IF NOT EXISTS generated_contents (
    id BIGSERIAL PRIMARY KEY,
    topic TEXT NOT NULL,
    audience TEXT NOT NULL,
    difficulty TEXT NOT NULL,
    language TEXT NOT NULL,
    lesson JSONB NOT NULL,
    skill JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
`

func (q *Queries) InitGeneratedContentsTable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, initGeneratedContentsTable)
	return err
}

const initGeneratedContentsTopicIndex = `-- name: InitGeneratedContentsTopicIndex :exec
CREATE INDEX IF NOT EXISTS idx_generated_contents_topic ON generated_contents (topic)
`

func (q *Queries) InitGeneratedContentsTopicIndex(ctx context.Context) error {
	_, err := q.db.Exec(ctx, initGeneratedContentsTopicIndex)
	return err
}

const initPromptCacheEntriesExpiresAtIndex = `-- name: InitPromptCacheEntriesExpiresAtIndex :exec
CREATE INDEX IF NOT EXISTS idx_prompt_cache_entries_expires_at ON prompt_cache_entries (expires_at)
`

func (q *Queries) InitPromptCacheEntriesExpiresAtIndex(ctx context.Context) error {
	_, err := q.db.Exec(ctx, initPromptCacheEntriesExpiresAtIndex)
	return err
}

const initPromptCacheEntriesTable = `-- name: InitPromptCacheEntriesTable :exec
CREATE TABLE IF NOT EXISTS prompt_cache_entries (
    cache_key TEXT PRIMARY KEY,
    response JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL
)
`

func (q *Queries) InitPromptCacheEntriesTable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, initPromptCacheEntriesTable)
	return err
}

const listGeneratedContents = `-- name: ListGeneratedContents :many
SELECT id, topic, audience, difficulty, language, lesson, skill, created_at
FROM generated_contents
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListGeneratedContents(ctx context.Context, limit int32) ([]GeneratedContent, error) {
	rows, err := q.db.Query(ctx, listGeneratedContents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeneratedContent
	for rows.Next() {
		var i GeneratedContent
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Audience,
			&i.Difficulty,
			&i.Language,
			&i.Lesson,
			&i.Skill,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const prunePromptCacheEntries = `-- name: PrunePromptCacheEntries :exec
DELETE FROM prompt_cache_entries
WHERE cache_key IN (
    SELECT cache_key
    FROM prompt_cache_entries
    ORDER BY created_at DESC
    OFFSET $1
)
`

func (q *Queries) PrunePromptCacheEntries(ctx context.Context, offset int32) error {
	_, err := q.db.Exec(ctx, prunePromptCacheEntries, offset)
	return err
}

const upsertPromptCacheEntry = `-- name: UpsertPromptCacheEntry :exec
INSERT INTO prompt_cache_entries (cache_key, response, expires_at)
VALUES ($1, $2, NOW() + ($3::int * INTERVAL '1 second'))
ON CONFLICT (cache_key) DO UPDATE
SET response = EXCLUDED.response,
    created_at = NOW(),
    expires_at = EXCLUDED.expires_at
`

type UpsertPromptCacheEntryParams struct {
	CacheKey   string `json:"cache_key"`
	Response   []byte `json:"response"`
	TtlSeconds int32  `json:"ttl_seconds"`
}

func (q *Queries) UpsertPromptCacheEntry(ctx context.Context, arg UpsertPromptCacheEntryParams) error {
	_, err := q.db.Exec(ctx, upsertPromptCacheEntry, arg.CacheKey, arg.Response, arg.TtlSeconds)
	return err
}
