package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type schemaEntry struct {
	Package string
	Schema  schema
}

type schema struct {
	ID         string              `json:"$id"`
	Title      string              `json:"title"`
	Type       any                 `json:"type"`
	Properties map[string]property `json:"properties"`
	Required   []string            `json:"required"`
}

type property struct {
	Type        any       `json:"type"`
	Items       *property `json:"items"`
	Default     any       `json:"default"`
	Description string    `json:"description"`
	Minimum     *float64  `json:"minimum"`
	Maximum     *float64  `json:"maximum"`
}

var (
	rootDir, _         = os.Getwd()
	schemaDir          = filepath.Join(rootDir, "packages", "shared-models", "schemas")
	webOut             = filepath.Join(rootDir, "apps", "web", "src", "models", "sharedModels.js")
	webPackageOutDir   = filepath.Join(rootDir, "apps", "web", "src", "models", "sharedModelsPackages")
	api2GoOutDir       = filepath.Join(rootDir, "apps", "api2", "internal", "sharedmodels")
	api2GoOut          = filepath.Join(api2GoOutDir, "models_gen.go")
	defaultCorePackage = "core"
)

func main() {
	entries, err := loadSchemaEntries()
	if err != nil {
		fatal(err)
	}
	if len(entries) == 0 {
		fatal(fmt.Errorf("no schemas found in %s", schemaDir))
	}

	packageModules, err := generatePackageOutputs(entries)
	if err != nil {
		fatal(err)
	}
	if err := writeFile(webOut, generateWebAggregateModule(packageModules)); err != nil {
		fatal(err)
	}
	if err := writeFile(api2GoOut, generateGoModels(entries)); err != nil {
		fatal(err)
	}

	fmt.Printf("Generated shared models for %d schemas\n", len(entries))
	fmt.Printf("- WEB (combined): %s\n", webOut)
	fmt.Printf("- WEB (by package): %s\n", webPackageOutDir)
	fmt.Printf("- API2 (Go): %s\n", api2GoOut)
}

func loadSchemaEntries() ([]schemaEntry, error) {
	entries := []schemaEntry{}

	err := filepath.WalkDir(schemaDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if !strings.HasSuffix(path, ".schema.json") || strings.HasPrefix(filepath.Base(path), ".") {
			return nil
		}

		relPath, err := filepath.Rel(schemaDir, path)
		if err != nil {
			return err
		}
		parts := strings.Split(relPath, string(filepath.Separator))
		pkg := defaultCorePackage
		if len(parts) > 1 {
			pkg = parts[0]
		}

		payload, err := os.ReadFile(path)
		if err != nil {
			return err
		}

		var s schema
		if err := json.Unmarshal(payload, &s); err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}
		if !isObjectSchema(s.Type) {
			return nil
		}
		if strings.TrimSpace(s.Title) == "" {
			base := strings.TrimSuffix(filepath.Base(path), ".schema.json")
			s.Title = pascalCase(base)
		}
		entries = append(entries, schemaEntry{Package: pkg, Schema: s})
		return nil
	})
	if err != nil {
		return nil, err
	}

	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Package != entries[j].Package {
			return entries[i].Package < entries[j].Package
		}
		return entries[i].Schema.Title < entries[j].Schema.Title
	})

	return entries, nil
}

func generatePackageOutputs(entries []schemaEntry) ([]packageModule, error) {
	byPackage := map[string][]schema{}
	for _, entry := range entries {
		byPackage[entry.Package] = append(byPackage[entry.Package], entry.Schema)
	}

	if err := os.MkdirAll(webPackageOutDir, 0o755); err != nil {
		return nil, err
	}
	if err := clearGeneratedFiles(webPackageOutDir, ".js"); err != nil {
		return nil, err
	}

	packages := make([]string, 0, len(byPackage))
	for pkg := range byPackage {
		packages = append(packages, pkg)
	}
	sort.Strings(packages)

	modules := make([]packageModule, 0, len(packages))
	for _, pkg := range packages {
		schemas := byPackage[pkg]
		moduleName := snakeCase(pkg)
		outPath := filepath.Join(webPackageOutDir, moduleName+".js")
		if err := writeFile(outPath, generateWebModel(schemas)); err != nil {
			return nil, err
		}
		classNames := make([]string, 0, len(schemas))
		for _, s := range schemas {
			classNames = append(classNames, s.Title)
		}
		modules = append(modules, packageModule{Package: pkg, ModuleName: moduleName, ClassNames: classNames})
	}

	if err := writeFile(filepath.Join(webPackageOutDir, "index.js"), generateWebPackageIndex(modules)); err != nil {
		return nil, err
	}

	return modules, nil
}

type packageModule struct {
	Package    string
	ModuleName string
	ClassNames []string
}

func generateWebAggregateModule(modules []packageModule) string {
	var b strings.Builder
	b.WriteString("// This file is auto-generated by scripts/generate_shared_models.go.\n")
	b.WriteString("// Do not edit manually.\n\n")
	for _, mod := range modules {
		if len(mod.ClassNames) == 0 {
			continue
		}
		b.WriteString(fmt.Sprintf("export { %s } from \"./sharedModelsPackages/%s.js\";\n", strings.Join(mod.ClassNames, ", "), mod.ModuleName))
	}
	b.WriteString("\n")
	return b.String()
}

func generateWebPackageIndex(modules []packageModule) string {
	var b strings.Builder
	b.WriteString("// This file is auto-generated by scripts/generate_shared_models.go.\n")
	b.WriteString("// Do not edit manually.\n\n")
	for _, mod := range modules {
		if len(mod.ClassNames) == 0 {
			continue
		}
		b.WriteString(fmt.Sprintf("export { %s } from \"./%s.js\";\n", strings.Join(mod.ClassNames, ", "), mod.ModuleName))
	}
	b.WriteString("\n")
	return b.String()
}

func generateWebModel(schemas []schema) string {
	var b strings.Builder
	b.WriteString("// This file is auto-generated by scripts/generate_shared_models.go.\n")
	b.WriteString("// Do not edit manually.\n\n")

	for _, s := range schemas {
		required := makeSet(s.Required)
		propNames := sortedKeys(s.Properties)
		b.WriteString("export class " + s.Title + " {\n")
		b.WriteString("  constructor(data = {}) {\n")
		for _, name := range propNames {
			prop := s.Properties[name]
			if prop.Default != nil {
				b.WriteString(fmt.Sprintf("    this.%s = data.%s ?? %s;\n", name, name, toJSValue(prop.Default)))
			} else {
				b.WriteString(fmt.Sprintf("    this.%s = data.%s;\n", name, name))
			}
		}
		b.WriteString("  }\n\n")

		b.WriteString("  static validate(data) {\n")
		for _, name := range propNames {
			prop := s.Properties[name]
			if required[name] {
				b.WriteString(fmt.Sprintf("    if (data.%s === undefined) return false;\n", name))
			}
			guard := jsGuardForProp(prop, "data."+name)
			b.WriteString(fmt.Sprintf("    if (data.%s !== undefined && !(%s)) return false;\n", name, guard))
			if prop.Minimum != nil {
				b.WriteString(fmt.Sprintf("    if (data.%s !== undefined && data.%s < %s) return false;\n", name, name, trimFloat(*prop.Minimum)))
			}
			if prop.Maximum != nil {
				b.WriteString(fmt.Sprintf("    if (data.%s !== undefined && data.%s > %s) return false;\n", name, name, trimFloat(*prop.Maximum)))
			}
		}
		b.WriteString("    return true;\n")
		b.WriteString("  }\n\n")

		b.WriteString("  toJSON() {\n")
		b.WriteString("    return {\n")
		for _, name := range propNames {
			b.WriteString(fmt.Sprintf("      %s: this.%s,\n", name, name))
		}
		b.WriteString("    };\n")
		b.WriteString("  }\n")
		b.WriteString("}\n\n")
	}

	return b.String()
}

func generateGoModels(entries []schemaEntry) string {
	var b strings.Builder
	b.WriteString("// Code generated by scripts/generate_shared_models.go. DO NOT EDIT.\n\n")
	b.WriteString("package sharedmodels\n\n")

	for _, entry := range entries {
		s := entry.Schema
		required := makeSet(s.Required)
		propNames := sortedKeys(s.Properties)
		b.WriteString("type " + s.Title + " struct {\n")
		for _, name := range propNames {
			prop := s.Properties[name]
			goType, optional := goTypeForProp(prop)
			if !required[name] || optional {
				if !strings.HasPrefix(goType, "[]") && !strings.HasPrefix(goType, "map[") && goType != "any" {
					goType = "*" + goType
				}
			}
			tag := fmt.Sprintf("`json:\"%s,omitempty\"`", name)
			if required[name] && !optional {
				tag = fmt.Sprintf("`json:\"%s\"`", name)
			}
			b.WriteString(fmt.Sprintf("\t%s %s %s\n", pascalCase(name), goType, tag))
		}
		b.WriteString("}\n\n")
	}

	return b.String()
}

func goTypeForProp(prop property) (string, bool) {
	types, nullable := normalizedTypes(prop.Type)
	if len(types) == 0 {
		return "any", nullable
	}

	t := types[0]
	switch t {
	case "string":
		return "string", nullable
	case "integer":
		return "int", nullable
	case "number":
		return "float64", nullable
	case "boolean":
		return "bool", nullable
	case "array":
		if prop.Items == nil {
			return "[]any", nullable
		}
		itemType, _ := goTypeForProp(*prop.Items)
		if itemType == "" {
			itemType = "any"
		}
		return "[]" + strings.TrimPrefix(itemType, "*"), nullable
	case "object":
		return "map[string]any", nullable
	default:
		return "any", nullable
	}
}

func jsGuardForProp(prop property, varName string) string {
	types, nullable := normalizedTypes(prop.Type)
	if len(types) == 0 {
		return "true"
	}
	t := types[0]

	var check string
	switch t {
	case "string":
		check = fmt.Sprintf("typeof %s === \"string\"", varName)
	case "integer":
		check = fmt.Sprintf("Number.isInteger(%s)", varName)
	case "number":
		check = fmt.Sprintf("typeof %s === \"number\"", varName)
	case "boolean":
		check = fmt.Sprintf("typeof %s === \"boolean\"", varName)
	case "array":
		itemGuard := "true"
		if prop.Items != nil {
			itemGuard = jsGuardForProp(*prop.Items, "item")
		}
		check = fmt.Sprintf("(Array.isArray(%s) && %s.every((item) => %s))", varName, varName, itemGuard)
	default:
		check = "true"
	}

	if nullable {
		return fmt.Sprintf("(%s === null || %s)", varName, check)
	}
	return check
}

func normalizedTypes(typeField any) ([]string, bool) {
	nullable := false
	switch v := typeField.(type) {
	case string:
		if v == "null" {
			return nil, true
		}
		return []string{v}, false
	case []any:
		types := []string{}
		for _, item := range v {
			s, ok := item.(string)
			if !ok {
				continue
			}
			if s == "null" {
				nullable = true
				continue
			}
			types = append(types, s)
		}
		return types, nullable
	default:
		return nil, false
	}
}

func isObjectSchema(typeField any) bool {
	types, _ := normalizedTypes(typeField)
	for _, t := range types {
		if t == "object" {
			return true
		}
	}
	return false
}

func pascalCase(value string) string {
	parts := strings.FieldsFunc(strings.ReplaceAll(value, "-", "_"), func(r rune) bool {
		return r == '_'
	})
	var b strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		if len(part) > 1 {
			b.WriteString(strings.ToLower(part[1:]))
		}
	}
	return b.String()
}

func snakeCase(value string) string {
	parts := strings.FieldsFunc(strings.ReplaceAll(value, "-", "_"), func(r rune) bool {
		return r == '_'
	})
	for i := range parts {
		parts[i] = strings.ToLower(parts[i])
	}
	return strings.Join(parts, "_")
}

func sortedKeys(m map[string]property) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func makeSet(items []string) map[string]bool {
	out := make(map[string]bool, len(items))
	for _, item := range items {
		out[item] = true
	}
	return out
}

func toJSValue(v any) string {
	b, err := json.Marshal(v)
	if err != nil {
		return "null"
	}
	return string(b)
}

func trimFloat(v float64) string {
	s := fmt.Sprintf("%g", v)
	if !strings.ContainsAny(s, ".eE") {
		return s
	}
	return s
}

func clearGeneratedFiles(dir, suffix string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if !strings.HasSuffix(entry.Name(), suffix) {
			continue
		}
		if err := os.Remove(filepath.Join(dir, entry.Name())); err != nil {
			return err
		}
	}
	return nil
}

func writeFile(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	buf := bytes.NewBufferString(content)
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

func fatal(err error) {
	fmt.Fprintf(os.Stderr, "error: %v\n", err)
	os.Exit(1)
}
