#!/usr/bin/env python3
import json
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA_DIR = ROOT / "packages" / "shared-models" / "schemas"
CORE_PACKAGE = "core"
API_OUT = ROOT / "apps" / "api" / "app" / "shared_models.py"
WEB_OUT = ROOT / "apps" / "web" / "src" / "models" / "sharedModels.js"
API_PACKAGE_OUT_DIR = ROOT / "apps" / "api" / "app" / "shared_models_packages"
WEB_PACKAGE_OUT_DIR = ROOT / "apps" / "web" / "src" / "models" / "sharedModelsPackages"

PY_TYPE_MAP = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
}

JS_TYPE_CHECKS = {
    "string": 'typeof value === "string"',
    "integer": 'Number.isInteger(value)',
    "number": 'typeof value === "number"',
    "boolean": 'typeof value === "boolean"',
}


@dataclass
class SchemaEntry:
    package: str
    schema: dict


def pascal_case(value: str) -> str:
    return "".join(part.capitalize() for part in value.replace("-", "_").split("_") if part)


def snake_case(value: str) -> str:
    parts = [part for part in value.replace("-", "_").split("_") if part]
    return "_".join(part.lower() for part in parts)


def python_type(prop: dict) -> str:
    prop_type = prop.get("type")
    if isinstance(prop_type, list):
        if "null" in prop_type:
            non_null = [t for t in prop_type if t != "null"]
            if len(non_null) == 1:
                return f"{python_type({**prop, 'type': non_null[0]})} | None"
            return "object | None"
        return "object"
    if prop_type == "array":
        item_type = python_type(prop.get("items", {}))
        item_type = item_type.replace(" | None", "")
        return f"list[{item_type}]"
    if prop_type == "object":
        return "dict[str, object]"
    return PY_TYPE_MAP.get(prop_type, "object")


def python_field_default(name: str, prop: dict, required: set[str]) -> str:
    default = prop.get("default", None)
    if name in required and "default" not in prop:
        return "..."
    if isinstance(default, list):
        return "Field(default_factory=list)"
    if isinstance(default, dict):
        return "Field(default_factory=dict)"
    if "minimum" in prop or "maximum" in prop or "description" in prop:
        attrs = []
        if name not in required and "default" not in prop:
            attrs.append("default=None")
        elif "default" in prop:
            attrs.append(f"default={default!r}")
        if "description" in prop:
            attrs.append(f"description={prop['description']!r}")
        if "minimum" in prop:
            attrs.append(f"ge={prop['minimum']!r}")
        if "maximum" in prop:
            attrs.append(f"le={prop['maximum']!r}")
        if attrs:
            return f"Field({', '.join(attrs)})"
    if "default" in prop:
        return repr(default)
    return "None"


def generate_api_model(schemas: list[dict]) -> str:
    lines = [
        "# This file is auto-generated by scripts/generate_shared_models.py.",
        "# Do not edit manually.",
        "",
        "from pydantic import BaseModel, Field",
        "",
    ]
    for schema in schemas:
        class_name = schema.get("title") or pascal_case(schema.get("$id", "Model"))
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))

        lines.append(f"class {class_name}(BaseModel):")
        if not properties:
            lines.append("    pass")
            lines.append("")
            continue

        for name, prop in properties.items():
            type_name = python_type(prop)
            if name not in required and "default" not in prop and "| None" not in type_name:
                type_name = f"{type_name} | None"
            default_expr = python_field_default(name, prop, required)
            lines.append(f"    {name}: {type_name} = {default_expr}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def js_guard_for_prop(prop: dict, var_name: str) -> str:
    prop_type = prop.get("type")
    if isinstance(prop_type, list):
        if "null" in prop_type and len(prop_type) == 2:
            inner = [t for t in prop_type if t != "null"][0]
            return f"({var_name} === null || {js_guard_for_prop({**prop, 'type': inner}, var_name)})"
        return "true"
    if prop_type == "array":
        item = prop.get("items", {})
        item_type = item.get("type")
        item_guard = js_guard_for_prop(item, "item")
        if item_type is None:
            item_guard = "true"
        return f"(Array.isArray({var_name}) && {var_name}.every((item) => {item_guard}))"
    check = JS_TYPE_CHECKS.get(prop_type)
    if check:
        return check.replace("value", var_name)
    return "true"


def generate_web_model(schemas: list[dict]) -> str:
    lines = [
        "// This file is auto-generated by scripts/generate_shared_models.py.",
        "// Do not edit manually.",
        "",
    ]

    for schema in schemas:
        class_name = schema.get("title") or pascal_case(schema.get("$id", "Model"))
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))

        lines.append(f"export class {class_name} " + "{")
        lines.append("  constructor(data = {}) {")
        for name, prop in properties.items():
            if "default" in prop:
                lines.append(f"    this.{name} = data.{name} ?? {json.dumps(prop['default'])};")
            else:
                lines.append(f"    this.{name} = data.{name};")
        lines.append("  }")
        lines.append("")
        lines.append("  static validate(data) {")
        for name, prop in properties.items():
            if name in required:
                lines.append(f"    if (data.{name} === undefined) return false;")
            guard = js_guard_for_prop(prop, f"data.{name}")
            lines.append(f"    if (data.{name} !== undefined && !({guard})) return false;")
            if prop.get("minimum") is not None:
                lines.append(f"    if (data.{name} !== undefined && data.{name} < {prop['minimum']}) return false;")
            if prop.get("maximum") is not None:
                lines.append(f"    if (data.{name} !== undefined && data.{name} > {prop['maximum']}) return false;")
        lines.append("    return true;")
        lines.append("  }")
        lines.append("")
        lines.append("  toJSON() {")
        lines.append("    return {")
        for name in properties:
            lines.append(f"      {name}: this.{name},")
        lines.append("    };")
        lines.append("  }")
        lines.append("}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def generate_api_aggregate_module(package_modules: list[tuple[str, str, list[str]]]) -> str:
    lines = [
        "# This file is auto-generated by scripts/generate_shared_models.py.",
        "# Do not edit manually.",
        "",
    ]
    all_exports: list[str] = []
    for _package, module_name, class_names in package_modules:
        if not class_names:
            continue
        joined = ", ".join(class_names)
        lines.append(f"from .shared_models_packages.{module_name} import {joined}")
        all_exports.extend(class_names)
    lines.append("")
    lines.append(f"__all__ = {all_exports!r}")
    lines.append("")
    return "\n".join(lines)


def generate_web_aggregate_module(package_modules: list[tuple[str, str, list[str]]]) -> str:
    lines = [
        "// This file is auto-generated by scripts/generate_shared_models.py.",
        "// Do not edit manually.",
        "",
    ]
    for _package, module_name, class_names in package_modules:
        if not class_names:
            continue
        joined = ", ".join(class_names)
        lines.append(f"export {{ {joined} }} from \"./sharedModelsPackages/{module_name}.js\";")
    lines.append("")
    return "\n".join(lines)


def load_schema_entries() -> list[SchemaEntry]:
    entries = []
    for path in sorted(SCHEMA_DIR.rglob("*.schema.json")):
        if path.name.startswith("."):
            continue
        rel_path = path.relative_to(SCHEMA_DIR)
        package = rel_path.parts[0] if len(rel_path.parts) > 1 else CORE_PACKAGE

        with path.open("r", encoding="utf-8") as f:
            schema = json.load(f)
            if schema.get("type") != "object":
                continue
            schema.setdefault("title", pascal_case(path.stem.replace(".schema", "")))
            entries.append(SchemaEntry(package=package, schema=schema))

    entries.sort(key=lambda item: (item.package, item.schema.get("title", "")))
    return entries


def clear_generated_files(out_dir: Path, pattern: str) -> None:
    if not out_dir.exists():
        return
    for path in out_dir.glob(pattern):
        if path.is_file():
            path.unlink()


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def generate_package_outputs(entries: list[SchemaEntry]) -> list[tuple[str, str, list[str]]]:
    by_package: dict[str, list[dict]] = defaultdict(list)
    for entry in entries:
        by_package[entry.package].append(entry.schema)

    API_PACKAGE_OUT_DIR.mkdir(parents=True, exist_ok=True)
    WEB_PACKAGE_OUT_DIR.mkdir(parents=True, exist_ok=True)
    clear_generated_files(API_PACKAGE_OUT_DIR, "*.py")
    clear_generated_files(WEB_PACKAGE_OUT_DIR, "*.js")

    package_modules: list[tuple[str, str, list[str]]] = []
    for package in sorted(by_package):
        schemas = by_package[package]
        module_name = snake_case(package)
        write_file(API_PACKAGE_OUT_DIR / f"{module_name}.py", generate_api_model(schemas))
        write_file(WEB_PACKAGE_OUT_DIR / f"{module_name}.js", generate_web_model(schemas))
        class_names = [schema["title"] for schema in schemas]
        package_modules.append((package, module_name, class_names))

    init_lines = [
        "# This file is auto-generated by scripts/generate_shared_models.py.",
        "# Do not edit manually.",
        "",
    ]
    all_exports: list[str] = []
    for _package, module_name, class_names in package_modules:
        if class_names:
            joined = ", ".join(class_names)
            init_lines.append(f"from .{module_name} import {joined}")
            all_exports.extend(class_names)
    init_lines.append("")
    init_lines.append(f"__all__ = {all_exports!r}")
    init_lines.append("")
    write_file(API_PACKAGE_OUT_DIR / "__init__.py", "\n".join(init_lines))

    index_lines = [
        "// This file is auto-generated by scripts/generate_shared_models.py.",
        "// Do not edit manually.",
        "",
    ]
    for _package, module_name, class_names in package_modules:
        if class_names:
            joined = ", ".join(class_names)
            index_lines.append(f"export {{ {joined} }} from \"./{module_name}.js\";")
    index_lines.append("")
    write_file(WEB_PACKAGE_OUT_DIR / "index.js", "\n".join(index_lines))
    return package_modules


def main() -> None:
    entries = load_schema_entries()
    if not entries:
        raise SystemExit(f"No schemas found in {SCHEMA_DIR}")

    legacy_top_level = sorted(
        path.name for path in SCHEMA_DIR.glob("*.schema.json") if path.is_file() and not path.name.startswith(".")
    )
    if legacy_top_level:
        joined = ", ".join(legacy_top_level)
        print(f"Warning: top-level schemas treated as '{CORE_PACKAGE}' package: {joined}")

    package_modules = generate_package_outputs(entries)
    write_file(API_OUT, generate_api_aggregate_module(package_modules))
    write_file(WEB_OUT, generate_web_aggregate_module(package_modules))

    schemas = [entry.schema for entry in entries]
    names = ", ".join(schema["title"] for schema in schemas)
    packages = ", ".join(sorted({entry.package for entry in entries}))
    print(f"Generated shared models for: {names}")
    print(f"Schema packages: {packages}")
    print(f"- API (combined): {API_OUT}")
    print(f"- WEB (combined): {WEB_OUT}")
    print(f"- API (by package): {API_PACKAGE_OUT_DIR}")
    print(f"- WEB (by package): {WEB_PACKAGE_OUT_DIR}")


if __name__ == "__main__":
    main()
