// Code generated by scripts/generate_shared_models.go. DO NOT EDIT.

package sharedmodels

type AnkiCard struct {
	BackText string `json:"back_text"`
	BloomLevel *string `json:"bloom_level,omitempty"`
	CreatedAt string `json:"created_at"`
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedTime *string `json:"created_time,omitempty"`
	DeckId *string `json:"deck_id,omitempty"`
	DueAt *string `json:"due_at,omitempty"`
	EaseFactor *float64 `json:"ease_factor,omitempty"`
	FrontText string `json:"front_text"`
	Id string `json:"id"`
	IntervalDays *int `json:"interval_days,omitempty"`
	IsSuspended *bool `json:"is_suspended,omitempty"`
	Lapses *int `json:"lapses,omitempty"`
	LastReviewedAt *string `json:"last_reviewed_at,omitempty"`
	Repetitions *int `json:"repetitions,omitempty"`
	SourceLessonId *string `json:"source_lesson_id,omitempty"`
	Status *string `json:"status,omitempty"`
	Tags []string `json:"tags,omitempty"`
	UpdatedAt string `json:"updated_at"`
	UpdatedBy *string `json:"updated_by,omitempty"`
	UpdatedTime *string `json:"updated_time,omitempty"`
	UserId string `json:"user_id"`
}

type AnkiDeck struct {
	CardCount *int `json:"card_count,omitempty"`
	CardIds []string `json:"card_ids,omitempty"`
	CreatedAt string `json:"created_at"`
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedTime *string `json:"created_time,omitempty"`
	Description *string `json:"description,omitempty"`
	Id string `json:"id"`
	IsArchived *bool `json:"is_archived,omitempty"`
	Name string `json:"name"`
	NewCardsPerDay *int `json:"new_cards_per_day,omitempty"`
	ReviewCardsPerDay *int `json:"review_cards_per_day,omitempty"`
	Tags []string `json:"tags,omitempty"`
	UpdatedAt string `json:"updated_at"`
	UpdatedBy *string `json:"updated_by,omitempty"`
	UpdatedTime *string `json:"updated_time,omitempty"`
	UserId string `json:"user_id"`
}

type AnkiReviewLog struct {
	CardId string `json:"card_id"`
	DeckId *string `json:"deck_id,omitempty"`
	EaseFactorAfter *float64 `json:"ease_factor_after,omitempty"`
	EaseFactorBefore *float64 `json:"ease_factor_before,omitempty"`
	ElapsedMs *int `json:"elapsed_ms,omitempty"`
	Id string `json:"id"`
	IntervalAfterDays *int `json:"interval_after_days,omitempty"`
	IntervalBeforeDays *int `json:"interval_before_days,omitempty"`
	Rating string `json:"rating"`
	ReviewedAt string `json:"reviewed_at"`
	UserId string `json:"user_id"`
}

type ReviewSession struct {
	CompletedAt *string `json:"completed_at,omitempty"`
	CreatedAt string `json:"created_at"`
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedTime *string `json:"created_time,omitempty"`
	DeckId *string `json:"deck_id,omitempty"`
	Id string `json:"id"`
	ReviewedCount *int `json:"reviewed_count,omitempty"`
	SelectedCardIds []string `json:"selected_card_ids,omitempty"`
	StartedAt *string `json:"started_at,omitempty"`
	Status *string `json:"status,omitempty"`
	TargetDurationMinutes int `json:"target_duration_minutes"`
	UpdatedAt string `json:"updated_at"`
	UpdatedBy *string `json:"updated_by,omitempty"`
	UpdatedTime *string `json:"updated_time,omitempty"`
	UserId string `json:"user_id"`
}

type Assessment struct {
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedTime *string `json:"created_time,omitempty"`
	Description *string `json:"description,omitempty"`
	ExpectedTimeMinutes int `json:"expected_time_minutes"`
	Id string `json:"id"`
	IsPublished *bool `json:"is_published,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Title string `json:"title"`
	Type string `json:"type"`
	UpdatedBy *string `json:"updated_by,omitempty"`
	UpdatedTime *string `json:"updated_time,omitempty"`
}

type Assignment struct {
	AssessmentId string `json:"assessment_id"`
	AssignedAt string `json:"assigned_at"`
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedTime *string `json:"created_time,omitempty"`
	Deadline string `json:"deadline"`
	Description *string `json:"description,omitempty"`
	Feedback *string `json:"feedback,omitempty"`
	Grade *float64 `json:"grade,omitempty"`
	Id string `json:"id"`
	LearnerId string `json:"learner_id"`
	Status *string `json:"status,omitempty"`
	SubmittedAt *string `json:"submitted_at,omitempty"`
	Title string `json:"title"`
	UpdatedBy *string `json:"updated_by,omitempty"`
	UpdatedTime *string `json:"updated_time,omitempty"`
}

type Book struct {
	Author *string `json:"author,omitempty"`
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedTime *string `json:"created_time,omitempty"`
	Id string `json:"id"`
	Isbn *string `json:"isbn,omitempty"`
	PublishedAt *string `json:"published_at,omitempty"`
	SourceId string `json:"source_id"`
	UpdatedBy *string `json:"updated_by,omitempty"`
	UpdatedTime *string `json:"updated_time,omitempty"`
}

type Chapter struct {
	BookId string `json:"book_id"`
	Content string `json:"content"`
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedTime *string `json:"created_time,omitempty"`
	Id string `json:"id"`
	Position *int `json:"position,omitempty"`
	Title string `json:"title"`
	UpdatedBy *string `json:"updated_by,omitempty"`
	UpdatedTime *string `json:"updated_time,omitempty"`
}

type Concept struct {
	CanonicalName string `json:"canonical_name"`
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedTime *string `json:"created_time,omitempty"`
	Description *string `json:"description,omitempty"`
	Domain *string `json:"domain,omitempty"`
	Id string `json:"id"`
	Tags []string `json:"tags,omitempty"`
	UpdatedBy *string `json:"updated_by,omitempty"`
	UpdatedTime *string `json:"updated_time,omitempty"`
}

type ConceptAlias struct {
	Alias string `json:"alias"`
	ConceptId string `json:"concept_id"`
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedTime *string `json:"created_time,omitempty"`
	Id string `json:"id"`
}

type ConceptRelation struct {
	ConceptAId string `json:"concept_a_id"`
	ConceptBId string `json:"concept_b_id"`
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedTime *string `json:"created_time,omitempty"`
	RelationType string `json:"relation_type"`
}

type Folder struct {
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedTime *string `json:"created_time,omitempty"`
	Description *string `json:"description,omitempty"`
	Domain *string `json:"domain,omitempty"`
	Id string `json:"id"`
	Name string `json:"name"`
	UpdatedBy *string `json:"updated_by,omitempty"`
	UpdatedTime *string `json:"updated_time,omitempty"`
}

type Lesson struct {
	ConceptId *string `json:"concept_id,omitempty"`
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedTime *string `json:"created_time,omitempty"`
	Description *string `json:"description,omitempty"`
	Difficulty *string `json:"difficulty,omitempty"`
	DurationMinutes *int `json:"duration_minutes,omitempty"`
	Id string `json:"id"`
	IsPublished *bool `json:"is_published,omitempty"`
	SourceId *string `json:"source_id,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Title string `json:"title"`
	Type *string `json:"type,omitempty"`
	UpdatedBy *string `json:"updated_by,omitempty"`
	UpdatedTime *string `json:"updated_time,omitempty"`
}

type Skill struct {
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedTime *string `json:"created_time,omitempty"`
	Description *string `json:"description,omitempty"`
	Difficulty *string `json:"difficulty,omitempty"`
	Id string `json:"id"`
	Status *string `json:"status,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Title string `json:"title"`
	UpdatedBy *string `json:"updated_by,omitempty"`
	UpdatedTime *string `json:"updated_time,omitempty"`
}

type SkillInput struct {
	Description *string `json:"description,omitempty"`
	Difficulty *string `json:"difficulty,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Title string `json:"title"`
}

type SkillLesson struct {
	CreatedAt *string `json:"created_at,omitempty"`
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedTime *string `json:"created_time,omitempty"`
	Id string `json:"id"`
	IsRequired *bool `json:"is_required,omitempty"`
	LessonId string `json:"lesson_id"`
	OrderIndex int `json:"order_index"`
	SkillId string `json:"skill_id"`
	UpdatedBy *string `json:"updated_by,omitempty"`
	UpdatedTime *string `json:"updated_time,omitempty"`
}

type Source struct {
	Content string `json:"content"`
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedTime *string `json:"created_time,omitempty"`
	FileUrl *string `json:"file_url,omitempty"`
	FolderId string `json:"folder_id"`
	Id string `json:"id"`
	Status *string `json:"status,omitempty"`
	Title *string `json:"title,omitempty"`
	Type *string `json:"type,omitempty"`
	UpdatedBy *string `json:"updated_by,omitempty"`
	UpdatedTime *string `json:"updated_time,omitempty"`
}

type SourceConcept struct {
	ConceptId string `json:"concept_id"`
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedTime *string `json:"created_time,omitempty"`
	SourceId string `json:"source_id"`
}

type SourceTopic struct {
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedTime *string `json:"created_time,omitempty"`
	SourceId string `json:"source_id"`
	TopicId string `json:"topic_id"`
}

type StudentPerformance struct {
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedTime *string `json:"created_time,omitempty"`
	CurrentScore float64 `json:"current_score"`
	Id string `json:"id"`
	LatestHistoryId *string `json:"latest_history_id,omitempty"`
	LearnerId string `json:"learner_id"`
	LevelFramework *string `json:"level_framework,omitempty"`
	LevelValue *string `json:"level_value,omitempty"`
	MeasuredAt string `json:"measured_at"`
	SkillId string `json:"skill_id"`
	Trend *string `json:"trend,omitempty"`
	UpdatedAt string `json:"updated_at"`
	UpdatedBy *string `json:"updated_by,omitempty"`
	UpdatedTime *string `json:"updated_time,omitempty"`
}

type StudentPerformanceSnapshot struct {
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedTime *string `json:"created_time,omitempty"`
	Id string `json:"id"`
	LearnerId string `json:"learner_id"`
	LevelFramework *string `json:"level_framework,omitempty"`
	LevelValue *string `json:"level_value,omitempty"`
	Notes *string `json:"notes,omitempty"`
	RecordedAt string `json:"recorded_at"`
	Score float64 `json:"score"`
	SkillId string `json:"skill_id"`
	Source *string `json:"source,omitempty"`
	StudentPerformanceId *string `json:"student_performance_id,omitempty"`
}

type StudentPerformanceTimeline struct {
	FromTime *string `json:"from_time,omitempty"`
	GeneratedAt string `json:"generated_at"`
	Id string `json:"id"`
	LearnerId string `json:"learner_id"`
	PerformanceTrends []map[string]any `json:"performance_trends,omitempty"`
	SkillId *string `json:"skill_id,omitempty"`
	Snapshots []map[string]any `json:"snapshots"`
	ToTime *string `json:"to_time,omitempty"`
}

type Topic struct {
	ConceptIds []string `json:"concept_ids,omitempty"`
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedTime *string `json:"created_time,omitempty"`
	Description *string `json:"description,omitempty"`
	FolderId string `json:"folder_id"`
	Id string `json:"id"`
	Name string `json:"name"`
	UpdatedBy *string `json:"updated_by,omitempty"`
	UpdatedTime *string `json:"updated_time,omitempty"`
}

type StudentProfile struct {
	Age int `json:"age"`
	CreatedAt string `json:"created_at"`
	CreatedBy *string `json:"created_by,omitempty"`
	CreatedTime *string `json:"created_time,omitempty"`
	EducationSystem *string `json:"education_system,omitempty"`
	Email string `json:"email"`
	FullName string `json:"full_name"`
	GradeLevel int `json:"grade_level"`
	Id string `json:"id"`
	Phone *string `json:"phone,omitempty"`
	UpdatedAt string `json:"updated_at"`
	UpdatedBy *string `json:"updated_by,omitempty"`
	UpdatedTime *string `json:"updated_time,omitempty"`
	UserId string `json:"user_id"`
}

