// This file is auto-generated by scripts/generate_shared_models.go.
// Do not edit manually.

interface AnkiCardData {
  back_text?: string
  created_at?: string
  created_by?: string | null
  created_time?: string | null
  deck_id?: string | null
  due_at?: string | null
  ease_factor?: number
  front_text?: string
  id?: string
  interval_days?: number
  is_suspended?: boolean
  lapses?: number
  last_reviewed_at?: string | null
  repetitions?: number
  source_lesson_id?: string | null
  status?: string
  tags?: string[]
  updated_at?: string
  updated_by?: string | null
  updated_time?: string | null
  user_id?: string
}

export class AnkiCard {
  back_text: string | undefined
  created_at: string | undefined
  created_by: string | null | undefined
  created_time: string | null | undefined
  deck_id: string | null | undefined
  due_at: string | null | undefined
  ease_factor: number
  front_text: string | undefined
  id: string | undefined
  interval_days: number
  is_suspended: boolean
  lapses: number
  last_reviewed_at: string | null | undefined
  repetitions: number
  source_lesson_id: string | null | undefined
  status: string
  tags: string[]
  updated_at: string | undefined
  updated_by: string | null | undefined
  updated_time: string | null | undefined
  user_id: string | undefined

  constructor(data: AnkiCardData = {}) {
    this.back_text = data.back_text;
    this.created_at = data.created_at;
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.deck_id = data.deck_id;
    this.due_at = data.due_at;
    this.ease_factor = data.ease_factor ?? 2.5;
    this.front_text = data.front_text;
    this.id = data.id;
    this.interval_days = data.interval_days ?? 0;
    this.is_suspended = data.is_suspended ?? false;
    this.lapses = data.lapses ?? 0;
    this.last_reviewed_at = data.last_reviewed_at;
    this.repetitions = data.repetitions ?? 0;
    this.source_lesson_id = data.source_lesson_id;
    this.status = data.status ?? "new";
    this.tags = data.tags ?? [];
    this.updated_at = data.updated_at;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
    this.user_id = data.user_id;
  }

  static validate(data: Record<string, unknown>): boolean {
    if (data.back_text === undefined) return false;
    if (data.back_text !== undefined && !(typeof data.back_text === "string")) return false;
    if (data.created_at === undefined) return false;
    if (data.created_at !== undefined && !(typeof data.created_at === "string")) return false;
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.deck_id !== undefined && !((data.deck_id === null || typeof data.deck_id === "string"))) return false;
    if (data.due_at !== undefined && !((data.due_at === null || typeof data.due_at === "string"))) return false;
    if (data.ease_factor !== undefined && !(typeof data.ease_factor === "number")) return false;
    if (data.ease_factor !== undefined && (data.ease_factor as number) < 1.3) return false;
    if (data.ease_factor !== undefined && (data.ease_factor as number) > 3) return false;
    if (data.front_text === undefined) return false;
    if (data.front_text !== undefined && !(typeof data.front_text === "string")) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.interval_days !== undefined && !(Number.isInteger(data.interval_days))) return false;
    if (data.interval_days !== undefined && (data.interval_days as number) < 0) return false;
    if (data.is_suspended !== undefined && !(typeof data.is_suspended === "boolean")) return false;
    if (data.lapses !== undefined && !(Number.isInteger(data.lapses))) return false;
    if (data.lapses !== undefined && (data.lapses as number) < 0) return false;
    if (data.last_reviewed_at !== undefined && !((data.last_reviewed_at === null || typeof data.last_reviewed_at === "string"))) return false;
    if (data.repetitions !== undefined && !(Number.isInteger(data.repetitions))) return false;
    if (data.repetitions !== undefined && (data.repetitions as number) < 0) return false;
    if (data.source_lesson_id !== undefined && !((data.source_lesson_id === null || typeof data.source_lesson_id === "string"))) return false;
    if (data.status !== undefined && !(typeof data.status === "string")) return false;
    if (data.tags !== undefined && !((Array.isArray(data.tags) && (data.tags as unknown[]).every((item) => typeof item === "string")))) return false;
    if (data.updated_at === undefined) return false;
    if (data.updated_at !== undefined && !(typeof data.updated_at === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    if (data.user_id === undefined) return false;
    if (data.user_id !== undefined && !(typeof data.user_id === "string")) return false;
    return true;
  }

  toJSON(): AnkiCardData {
    return {
      back_text: this.back_text,
      created_at: this.created_at,
      created_by: this.created_by,
      created_time: this.created_time,
      deck_id: this.deck_id,
      due_at: this.due_at,
      ease_factor: this.ease_factor,
      front_text: this.front_text,
      id: this.id,
      interval_days: this.interval_days,
      is_suspended: this.is_suspended,
      lapses: this.lapses,
      last_reviewed_at: this.last_reviewed_at,
      repetitions: this.repetitions,
      source_lesson_id: this.source_lesson_id,
      status: this.status,
      tags: this.tags,
      updated_at: this.updated_at,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
      user_id: this.user_id,
    };
  }
}

interface AnkiDeckData {
  card_count?: number
  card_ids?: string[] | null
  created_at?: string
  created_by?: string | null
  created_time?: string | null
  description?: string | null
  id?: string
  is_archived?: boolean
  name?: string
  new_cards_per_day?: number
  review_cards_per_day?: number
  tags?: string[]
  updated_at?: string
  updated_by?: string | null
  updated_time?: string | null
  user_id?: string
}

export class AnkiDeck {
  card_count: number
  card_ids: string[] | null | undefined
  created_at: string | undefined
  created_by: string | null | undefined
  created_time: string | null | undefined
  description: string | null | undefined
  id: string | undefined
  is_archived: boolean
  name: string | undefined
  new_cards_per_day: number
  review_cards_per_day: number
  tags: string[]
  updated_at: string | undefined
  updated_by: string | null | undefined
  updated_time: string | null | undefined
  user_id: string | undefined

  constructor(data: AnkiDeckData = {}) {
    this.card_count = data.card_count ?? 0;
    this.card_ids = data.card_ids;
    this.created_at = data.created_at;
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.description = data.description;
    this.id = data.id;
    this.is_archived = data.is_archived ?? false;
    this.name = data.name;
    this.new_cards_per_day = data.new_cards_per_day ?? 20;
    this.review_cards_per_day = data.review_cards_per_day ?? 200;
    this.tags = data.tags ?? [];
    this.updated_at = data.updated_at;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
    this.user_id = data.user_id;
  }

  static validate(data: Record<string, unknown>): boolean {
    if (data.card_count !== undefined && !(Number.isInteger(data.card_count))) return false;
    if (data.card_count !== undefined && (data.card_count as number) < 0) return false;
    if (data.card_ids !== undefined && !((data.card_ids === null || (Array.isArray(data.card_ids) && (data.card_ids as unknown[]).every((item) => typeof item === "string"))))) return false;
    if (data.created_at === undefined) return false;
    if (data.created_at !== undefined && !(typeof data.created_at === "string")) return false;
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.description !== undefined && !((data.description === null || typeof data.description === "string"))) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.is_archived !== undefined && !(typeof data.is_archived === "boolean")) return false;
    if (data.name === undefined) return false;
    if (data.name !== undefined && !(typeof data.name === "string")) return false;
    if (data.new_cards_per_day !== undefined && !(Number.isInteger(data.new_cards_per_day))) return false;
    if (data.new_cards_per_day !== undefined && (data.new_cards_per_day as number) < 0) return false;
    if (data.review_cards_per_day !== undefined && !(Number.isInteger(data.review_cards_per_day))) return false;
    if (data.review_cards_per_day !== undefined && (data.review_cards_per_day as number) < 0) return false;
    if (data.tags !== undefined && !((Array.isArray(data.tags) && (data.tags as unknown[]).every((item) => typeof item === "string")))) return false;
    if (data.updated_at === undefined) return false;
    if (data.updated_at !== undefined && !(typeof data.updated_at === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    if (data.user_id === undefined) return false;
    if (data.user_id !== undefined && !(typeof data.user_id === "string")) return false;
    return true;
  }

  toJSON(): AnkiDeckData {
    return {
      card_count: this.card_count,
      card_ids: this.card_ids,
      created_at: this.created_at,
      created_by: this.created_by,
      created_time: this.created_time,
      description: this.description,
      id: this.id,
      is_archived: this.is_archived,
      name: this.name,
      new_cards_per_day: this.new_cards_per_day,
      review_cards_per_day: this.review_cards_per_day,
      tags: this.tags,
      updated_at: this.updated_at,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
      user_id: this.user_id,
    };
  }
}

interface AnkiReviewLogData {
  card_id?: string
  deck_id?: string | null
  ease_factor_after?: number
  ease_factor_before?: number
  elapsed_ms?: number
  id?: string
  interval_after_days?: number
  interval_before_days?: number
  rating?: string
  reviewed_at?: string
  user_id?: string
}

export class AnkiReviewLog {
  card_id: string | undefined
  deck_id: string | null | undefined
  ease_factor_after: number
  ease_factor_before: number
  elapsed_ms: number
  id: string | undefined
  interval_after_days: number
  interval_before_days: number
  rating: string | undefined
  reviewed_at: string | undefined
  user_id: string | undefined

  constructor(data: AnkiReviewLogData = {}) {
    this.card_id = data.card_id;
    this.deck_id = data.deck_id;
    this.ease_factor_after = data.ease_factor_after ?? 2.5;
    this.ease_factor_before = data.ease_factor_before ?? 2.5;
    this.elapsed_ms = data.elapsed_ms ?? 0;
    this.id = data.id;
    this.interval_after_days = data.interval_after_days ?? 0;
    this.interval_before_days = data.interval_before_days ?? 0;
    this.rating = data.rating;
    this.reviewed_at = data.reviewed_at;
    this.user_id = data.user_id;
  }

  static validate(data: Record<string, unknown>): boolean {
    if (data.card_id === undefined) return false;
    if (data.card_id !== undefined && !(typeof data.card_id === "string")) return false;
    if (data.deck_id !== undefined && !((data.deck_id === null || typeof data.deck_id === "string"))) return false;
    if (data.ease_factor_after !== undefined && !(typeof data.ease_factor_after === "number")) return false;
    if (data.ease_factor_after !== undefined && (data.ease_factor_after as number) < 1.3) return false;
    if (data.ease_factor_after !== undefined && (data.ease_factor_after as number) > 3) return false;
    if (data.ease_factor_before !== undefined && !(typeof data.ease_factor_before === "number")) return false;
    if (data.ease_factor_before !== undefined && (data.ease_factor_before as number) < 1.3) return false;
    if (data.ease_factor_before !== undefined && (data.ease_factor_before as number) > 3) return false;
    if (data.elapsed_ms !== undefined && !(Number.isInteger(data.elapsed_ms))) return false;
    if (data.elapsed_ms !== undefined && (data.elapsed_ms as number) < 0) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.interval_after_days !== undefined && !(Number.isInteger(data.interval_after_days))) return false;
    if (data.interval_after_days !== undefined && (data.interval_after_days as number) < 0) return false;
    if (data.interval_before_days !== undefined && !(Number.isInteger(data.interval_before_days))) return false;
    if (data.interval_before_days !== undefined && (data.interval_before_days as number) < 0) return false;
    if (data.rating === undefined) return false;
    if (data.rating !== undefined && !(typeof data.rating === "string")) return false;
    if (data.reviewed_at === undefined) return false;
    if (data.reviewed_at !== undefined && !(typeof data.reviewed_at === "string")) return false;
    if (data.user_id === undefined) return false;
    if (data.user_id !== undefined && !(typeof data.user_id === "string")) return false;
    return true;
  }

  toJSON(): AnkiReviewLogData {
    return {
      card_id: this.card_id,
      deck_id: this.deck_id,
      ease_factor_after: this.ease_factor_after,
      ease_factor_before: this.ease_factor_before,
      elapsed_ms: this.elapsed_ms,
      id: this.id,
      interval_after_days: this.interval_after_days,
      interval_before_days: this.interval_before_days,
      rating: this.rating,
      reviewed_at: this.reviewed_at,
      user_id: this.user_id,
    };
  }
}

interface ReviewSessionData {
  completed_at?: string | null
  created_at?: string
  created_by?: string | null
  created_time?: string | null
  deck_id?: string | null
  id?: string
  reviewed_count?: number
  selected_card_ids?: string[]
  started_at?: string | null
  status?: string
  target_duration_minutes?: number
  updated_at?: string
  updated_by?: string | null
  updated_time?: string | null
  user_id?: string
}

export class ReviewSession {
  completed_at: string | null | undefined
  created_at: string | undefined
  created_by: string | null | undefined
  created_time: string | null | undefined
  deck_id: string | null | undefined
  id: string | undefined
  reviewed_count: number
  selected_card_ids: string[]
  started_at: string | null | undefined
  status: string
  target_duration_minutes: number
  updated_at: string | undefined
  updated_by: string | null | undefined
  updated_time: string | null | undefined
  user_id: string | undefined

  constructor(data: ReviewSessionData = {}) {
    this.completed_at = data.completed_at;
    this.created_at = data.created_at;
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.deck_id = data.deck_id;
    this.id = data.id;
    this.reviewed_count = data.reviewed_count ?? 0;
    this.selected_card_ids = data.selected_card_ids ?? [];
    this.started_at = data.started_at;
    this.status = data.status ?? "planned";
    this.target_duration_minutes = data.target_duration_minutes ?? 10;
    this.updated_at = data.updated_at;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
    this.user_id = data.user_id;
  }

  static validate(data: Record<string, unknown>): boolean {
    if (data.completed_at !== undefined && !((data.completed_at === null || typeof data.completed_at === "string"))) return false;
    if (data.created_at === undefined) return false;
    if (data.created_at !== undefined && !(typeof data.created_at === "string")) return false;
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.deck_id !== undefined && !((data.deck_id === null || typeof data.deck_id === "string"))) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.reviewed_count !== undefined && !(Number.isInteger(data.reviewed_count))) return false;
    if (data.reviewed_count !== undefined && (data.reviewed_count as number) < 0) return false;
    if (data.selected_card_ids !== undefined && !((Array.isArray(data.selected_card_ids) && (data.selected_card_ids as unknown[]).every((item) => typeof item === "string")))) return false;
    if (data.started_at !== undefined && !((data.started_at === null || typeof data.started_at === "string"))) return false;
    if (data.status !== undefined && !(typeof data.status === "string")) return false;
    if (data.target_duration_minutes === undefined) return false;
    if (data.target_duration_minutes !== undefined && !(Number.isInteger(data.target_duration_minutes))) return false;
    if (data.target_duration_minutes !== undefined && (data.target_duration_minutes as number) < 1) return false;
    if (data.updated_at === undefined) return false;
    if (data.updated_at !== undefined && !(typeof data.updated_at === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    if (data.user_id === undefined) return false;
    if (data.user_id !== undefined && !(typeof data.user_id === "string")) return false;
    return true;
  }

  toJSON(): ReviewSessionData {
    return {
      completed_at: this.completed_at,
      created_at: this.created_at,
      created_by: this.created_by,
      created_time: this.created_time,
      deck_id: this.deck_id,
      id: this.id,
      reviewed_count: this.reviewed_count,
      selected_card_ids: this.selected_card_ids,
      started_at: this.started_at,
      status: this.status,
      target_duration_minutes: this.target_duration_minutes,
      updated_at: this.updated_at,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
      user_id: this.user_id,
    };
  }
}
