// This file is auto-generated by scripts/generate_shared_models.py.
// Do not edit manually.

export class AnkiCard {
  constructor(data = {}) {
    this.id = data.id;
    this.user_id = data.user_id;
    this.deck_id = data.deck_id ?? null;
    this.source_lesson_id = data.source_lesson_id ?? null;
    this.front_text = data.front_text;
    this.back_text = data.back_text;
    this.status = data.status ?? "new";
    this.ease_factor = data.ease_factor ?? 2.5;
    this.interval_days = data.interval_days ?? 0;
    this.repetitions = data.repetitions ?? 0;
    this.lapses = data.lapses ?? 0;
    this.due_at = data.due_at ?? null;
    this.last_reviewed_at = data.last_reviewed_at ?? null;
    this.is_suspended = data.is_suspended ?? false;
    this.tags = data.tags ?? [];
    this.created_at = data.created_at;
    this.updated_at = data.updated_at;
  }

  static validate(data) {
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.user_id === undefined) return false;
    if (data.user_id !== undefined && !(typeof data.user_id === "string")) return false;
    if (data.deck_id !== undefined && !((data.deck_id === null || typeof data.deck_id === "string"))) return false;
    if (data.source_lesson_id !== undefined && !((data.source_lesson_id === null || typeof data.source_lesson_id === "string"))) return false;
    if (data.front_text === undefined) return false;
    if (data.front_text !== undefined && !(typeof data.front_text === "string")) return false;
    if (data.back_text === undefined) return false;
    if (data.back_text !== undefined && !(typeof data.back_text === "string")) return false;
    if (data.status !== undefined && !(typeof data.status === "string")) return false;
    if (data.ease_factor !== undefined && !(typeof data.ease_factor === "number")) return false;
    if (data.ease_factor !== undefined && data.ease_factor < 1.3) return false;
    if (data.ease_factor !== undefined && data.ease_factor > 3) return false;
    if (data.interval_days !== undefined && !(Number.isInteger(data.interval_days))) return false;
    if (data.interval_days !== undefined && data.interval_days < 0) return false;
    if (data.repetitions !== undefined && !(Number.isInteger(data.repetitions))) return false;
    if (data.repetitions !== undefined && data.repetitions < 0) return false;
    if (data.lapses !== undefined && !(Number.isInteger(data.lapses))) return false;
    if (data.lapses !== undefined && data.lapses < 0) return false;
    if (data.due_at !== undefined && !((data.due_at === null || typeof data.due_at === "string"))) return false;
    if (data.last_reviewed_at !== undefined && !((data.last_reviewed_at === null || typeof data.last_reviewed_at === "string"))) return false;
    if (data.is_suspended !== undefined && !(typeof data.is_suspended === "boolean")) return false;
    if (data.tags !== undefined && !((Array.isArray(data.tags) && data.tags.every((item) => typeof item === "string")))) return false;
    if (data.created_at === undefined) return false;
    if (data.created_at !== undefined && !(typeof data.created_at === "string")) return false;
    if (data.updated_at === undefined) return false;
    if (data.updated_at !== undefined && !(typeof data.updated_at === "string")) return false;
    return true;
  }

  toJSON() {
    return {
      id: this.id,
      user_id: this.user_id,
      deck_id: this.deck_id,
      source_lesson_id: this.source_lesson_id,
      front_text: this.front_text,
      back_text: this.back_text,
      status: this.status,
      ease_factor: this.ease_factor,
      interval_days: this.interval_days,
      repetitions: this.repetitions,
      lapses: this.lapses,
      due_at: this.due_at,
      last_reviewed_at: this.last_reviewed_at,
      is_suspended: this.is_suspended,
      tags: this.tags,
      created_at: this.created_at,
      updated_at: this.updated_at,
    };
  }
}

export class AnkiDeck {
  constructor(data = {}) {
    this.id = data.id;
    this.user_id = data.user_id;
    this.name = data.name;
    this.description = data.description ?? null;
    this.is_archived = data.is_archived ?? false;
    this.new_cards_per_day = data.new_cards_per_day ?? 20;
    this.review_cards_per_day = data.review_cards_per_day ?? 200;
    this.card_count = data.card_count ?? 0;
    this.card_ids = data.card_ids ?? null;
    this.tags = data.tags ?? [];
    this.created_at = data.created_at;
    this.updated_at = data.updated_at;
  }

  static validate(data) {
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.user_id === undefined) return false;
    if (data.user_id !== undefined && !(typeof data.user_id === "string")) return false;
    if (data.name === undefined) return false;
    if (data.name !== undefined && !(typeof data.name === "string")) return false;
    if (data.description !== undefined && !((data.description === null || typeof data.description === "string"))) return false;
    if (data.is_archived !== undefined && !(typeof data.is_archived === "boolean")) return false;
    if (data.new_cards_per_day !== undefined && !(Number.isInteger(data.new_cards_per_day))) return false;
    if (data.new_cards_per_day !== undefined && data.new_cards_per_day < 0) return false;
    if (data.review_cards_per_day !== undefined && !(Number.isInteger(data.review_cards_per_day))) return false;
    if (data.review_cards_per_day !== undefined && data.review_cards_per_day < 0) return false;
    if (data.card_count !== undefined && !(Number.isInteger(data.card_count))) return false;
    if (data.card_count !== undefined && data.card_count < 0) return false;
    if (data.card_ids !== undefined && !((data.card_ids === null || (Array.isArray(data.card_ids) && data.card_ids.every((item) => typeof item === "string"))))) return false;
    if (data.tags !== undefined && !((Array.isArray(data.tags) && data.tags.every((item) => typeof item === "string")))) return false;
    if (data.created_at === undefined) return false;
    if (data.created_at !== undefined && !(typeof data.created_at === "string")) return false;
    if (data.updated_at === undefined) return false;
    if (data.updated_at !== undefined && !(typeof data.updated_at === "string")) return false;
    return true;
  }

  toJSON() {
    return {
      id: this.id,
      user_id: this.user_id,
      name: this.name,
      description: this.description,
      is_archived: this.is_archived,
      new_cards_per_day: this.new_cards_per_day,
      review_cards_per_day: this.review_cards_per_day,
      card_count: this.card_count,
      card_ids: this.card_ids,
      tags: this.tags,
      created_at: this.created_at,
      updated_at: this.updated_at,
    };
  }
}

export class AnkiReviewLog {
  constructor(data = {}) {
    this.id = data.id;
    this.user_id = data.user_id;
    this.card_id = data.card_id;
    this.deck_id = data.deck_id ?? null;
    this.rating = data.rating;
    this.elapsed_ms = data.elapsed_ms ?? 0;
    this.interval_before_days = data.interval_before_days ?? 0;
    this.interval_after_days = data.interval_after_days ?? 0;
    this.ease_factor_before = data.ease_factor_before ?? 2.5;
    this.ease_factor_after = data.ease_factor_after ?? 2.5;
    this.reviewed_at = data.reviewed_at;
  }

  static validate(data) {
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.user_id === undefined) return false;
    if (data.user_id !== undefined && !(typeof data.user_id === "string")) return false;
    if (data.card_id === undefined) return false;
    if (data.card_id !== undefined && !(typeof data.card_id === "string")) return false;
    if (data.deck_id !== undefined && !((data.deck_id === null || typeof data.deck_id === "string"))) return false;
    if (data.rating === undefined) return false;
    if (data.rating !== undefined && !(typeof data.rating === "string")) return false;
    if (data.elapsed_ms !== undefined && !(Number.isInteger(data.elapsed_ms))) return false;
    if (data.elapsed_ms !== undefined && data.elapsed_ms < 0) return false;
    if (data.interval_before_days !== undefined && !(Number.isInteger(data.interval_before_days))) return false;
    if (data.interval_before_days !== undefined && data.interval_before_days < 0) return false;
    if (data.interval_after_days !== undefined && !(Number.isInteger(data.interval_after_days))) return false;
    if (data.interval_after_days !== undefined && data.interval_after_days < 0) return false;
    if (data.ease_factor_before !== undefined && !(typeof data.ease_factor_before === "number")) return false;
    if (data.ease_factor_before !== undefined && data.ease_factor_before < 1.3) return false;
    if (data.ease_factor_before !== undefined && data.ease_factor_before > 3) return false;
    if (data.ease_factor_after !== undefined && !(typeof data.ease_factor_after === "number")) return false;
    if (data.ease_factor_after !== undefined && data.ease_factor_after < 1.3) return false;
    if (data.ease_factor_after !== undefined && data.ease_factor_after > 3) return false;
    if (data.reviewed_at === undefined) return false;
    if (data.reviewed_at !== undefined && !(typeof data.reviewed_at === "string")) return false;
    return true;
  }

  toJSON() {
    return {
      id: this.id,
      user_id: this.user_id,
      card_id: this.card_id,
      deck_id: this.deck_id,
      rating: this.rating,
      elapsed_ms: this.elapsed_ms,
      interval_before_days: this.interval_before_days,
      interval_after_days: this.interval_after_days,
      ease_factor_before: this.ease_factor_before,
      ease_factor_after: this.ease_factor_after,
      reviewed_at: this.reviewed_at,
    };
  }
}

export class ReviewSession {
  constructor(data = {}) {
    this.id = data.id;
    this.user_id = data.user_id;
    this.deck_id = data.deck_id ?? null;
    this.target_duration_minutes = data.target_duration_minutes ?? 10;
    this.status = data.status ?? "planned";
    this.selected_card_ids = data.selected_card_ids ?? [];
    this.reviewed_count = data.reviewed_count ?? 0;
    this.started_at = data.started_at ?? null;
    this.completed_at = data.completed_at ?? null;
    this.created_at = data.created_at;
    this.updated_at = data.updated_at;
  }

  static validate(data) {
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.user_id === undefined) return false;
    if (data.user_id !== undefined && !(typeof data.user_id === "string")) return false;
    if (data.deck_id !== undefined && !((data.deck_id === null || typeof data.deck_id === "string"))) return false;
    if (data.target_duration_minutes === undefined) return false;
    if (data.target_duration_minutes !== undefined && !(Number.isInteger(data.target_duration_minutes))) return false;
    if (data.target_duration_minutes !== undefined && data.target_duration_minutes < 1) return false;
    if (data.status !== undefined && !(typeof data.status === "string")) return false;
    if (data.selected_card_ids !== undefined && !((Array.isArray(data.selected_card_ids) && data.selected_card_ids.every((item) => typeof item === "string")))) return false;
    if (data.reviewed_count !== undefined && !(Number.isInteger(data.reviewed_count))) return false;
    if (data.reviewed_count !== undefined && data.reviewed_count < 0) return false;
    if (data.started_at !== undefined && !((data.started_at === null || typeof data.started_at === "string"))) return false;
    if (data.completed_at !== undefined && !((data.completed_at === null || typeof data.completed_at === "string"))) return false;
    if (data.created_at === undefined) return false;
    if (data.created_at !== undefined && !(typeof data.created_at === "string")) return false;
    if (data.updated_at === undefined) return false;
    if (data.updated_at !== undefined && !(typeof data.updated_at === "string")) return false;
    return true;
  }

  toJSON() {
    return {
      id: this.id,
      user_id: this.user_id,
      deck_id: this.deck_id,
      target_duration_minutes: this.target_duration_minutes,
      status: this.status,
      selected_card_ids: this.selected_card_ids,
      reviewed_count: this.reviewed_count,
      started_at: this.started_at,
      completed_at: this.completed_at,
      created_at: this.created_at,
      updated_at: this.updated_at,
    };
  }
}
