// This file is auto-generated by scripts/generate_shared_models.go.
// Do not edit manually.

export class Assessment {
  constructor(data = {}) {
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.description = data.description;
    this.expected_time_minutes = data.expected_time_minutes;
    this.id = data.id;
    this.is_published = data.is_published ?? false;
    this.tags = data.tags ?? [];
    this.title = data.title;
    this.type = data.type;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data) {
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.description !== undefined && !(typeof data.description === "string")) return false;
    if (data.expected_time_minutes === undefined) return false;
    if (data.expected_time_minutes !== undefined && !(Number.isInteger(data.expected_time_minutes))) return false;
    if (data.expected_time_minutes !== undefined && data.expected_time_minutes < 1) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.is_published !== undefined && !(typeof data.is_published === "boolean")) return false;
    if (data.tags !== undefined && !((Array.isArray(data.tags) && data.tags.every((item) => typeof item === "string")))) return false;
    if (data.title === undefined) return false;
    if (data.title !== undefined && !(typeof data.title === "string")) return false;
    if (data.type === undefined) return false;
    if (data.type !== undefined && !(typeof data.type === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      created_by: this.created_by,
      created_time: this.created_time,
      description: this.description,
      expected_time_minutes: this.expected_time_minutes,
      id: this.id,
      is_published: this.is_published,
      tags: this.tags,
      title: this.title,
      type: this.type,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

export class Assignment {
  constructor(data = {}) {
    this.assessment_id = data.assessment_id;
    this.assigned_at = data.assigned_at;
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.deadline = data.deadline;
    this.description = data.description;
    this.feedback = data.feedback;
    this.grade = data.grade;
    this.id = data.id;
    this.learner_id = data.learner_id;
    this.status = data.status ?? "assigned";
    this.submitted_at = data.submitted_at;
    this.title = data.title;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data) {
    if (data.assessment_id === undefined) return false;
    if (data.assessment_id !== undefined && !(typeof data.assessment_id === "string")) return false;
    if (data.assigned_at === undefined) return false;
    if (data.assigned_at !== undefined && !(typeof data.assigned_at === "string")) return false;
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.deadline === undefined) return false;
    if (data.deadline !== undefined && !(typeof data.deadline === "string")) return false;
    if (data.description !== undefined && !(typeof data.description === "string")) return false;
    if (data.feedback !== undefined && !((data.feedback === null || typeof data.feedback === "string"))) return false;
    if (data.grade !== undefined && !((data.grade === null || typeof data.grade === "number"))) return false;
    if (data.grade !== undefined && data.grade < 0) return false;
    if (data.grade !== undefined && data.grade > 100) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.learner_id === undefined) return false;
    if (data.learner_id !== undefined && !(typeof data.learner_id === "string")) return false;
    if (data.status !== undefined && !(typeof data.status === "string")) return false;
    if (data.submitted_at !== undefined && !((data.submitted_at === null || typeof data.submitted_at === "string"))) return false;
    if (data.title === undefined) return false;
    if (data.title !== undefined && !(typeof data.title === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      assessment_id: this.assessment_id,
      assigned_at: this.assigned_at,
      created_by: this.created_by,
      created_time: this.created_time,
      deadline: this.deadline,
      description: this.description,
      feedback: this.feedback,
      grade: this.grade,
      id: this.id,
      learner_id: this.learner_id,
      status: this.status,
      submitted_at: this.submitted_at,
      title: this.title,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

