// This file is auto-generated by scripts/generate_shared_models.go.
// Do not edit manually.

export class Book {
  constructor(data = {}) {
    this.author = data.author;
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.id = data.id;
    this.isbn = data.isbn;
    this.published_at = data.published_at;
    this.source_id = data.source_id;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data) {
    if (data.author !== undefined && !((data.author === null || typeof data.author === "string"))) return false;
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.isbn !== undefined && !((data.isbn === null || typeof data.isbn === "string"))) return false;
    if (data.published_at !== undefined && !((data.published_at === null || typeof data.published_at === "string"))) return false;
    if (data.source_id === undefined) return false;
    if (data.source_id !== undefined && !(typeof data.source_id === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      author: this.author,
      created_by: this.created_by,
      created_time: this.created_time,
      id: this.id,
      isbn: this.isbn,
      published_at: this.published_at,
      source_id: this.source_id,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

export class Chapter {
  constructor(data = {}) {
    this.book_id = data.book_id;
    this.content = data.content;
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.id = data.id;
    this.position = data.position;
    this.title = data.title;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data) {
    if (data.book_id === undefined) return false;
    if (data.book_id !== undefined && !(typeof data.book_id === "string")) return false;
    if (data.content === undefined) return false;
    if (data.content !== undefined && !(typeof data.content === "string")) return false;
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.position !== undefined && !((data.position === null || Number.isInteger(data.position)))) return false;
    if (data.title === undefined) return false;
    if (data.title !== undefined && !(typeof data.title === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      book_id: this.book_id,
      content: this.content,
      created_by: this.created_by,
      created_time: this.created_time,
      id: this.id,
      position: this.position,
      title: this.title,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

export class Folder {
  constructor(data = {}) {
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.description = data.description;
    this.domain = data.domain;
    this.folder_type = data.folder_type;
    this.icon = data.icon;
    this.id = data.id;
    this.is_locked = data.is_locked ?? false;
    this.name = data.name;
    this.owner_id = data.owner_id;
    this.program_id = data.program_id;
    this.theme = data.theme;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data) {
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.description !== undefined && !(typeof data.description === "string")) return false;
    if (data.domain !== undefined && !((data.domain === null || typeof data.domain === "string"))) return false;
    if (data.folder_type === undefined) return false;
    if (data.folder_type !== undefined && !(typeof data.folder_type === "string")) return false;
    if (data.icon !== undefined && !((data.icon === null || typeof data.icon === "string"))) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.is_locked !== undefined && !(typeof data.is_locked === "boolean")) return false;
    if (data.name === undefined) return false;
    if (data.name !== undefined && !(typeof data.name === "string")) return false;
    if (data.owner_id !== undefined && !((data.owner_id === null || typeof data.owner_id === "string"))) return false;
    if (data.program_id !== undefined && !((data.program_id === null || typeof data.program_id === "string"))) return false;
    if (data.theme !== undefined && !((data.theme === null || typeof data.theme === "string"))) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      created_by: this.created_by,
      created_time: this.created_time,
      description: this.description,
      domain: this.domain,
      folder_type: this.folder_type,
      icon: this.icon,
      id: this.id,
      is_locked: this.is_locked,
      name: this.name,
      owner_id: this.owner_id,
      program_id: this.program_id,
      theme: this.theme,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

export class FolderMember {
  constructor(data = {}) {
    this.added_by = data.added_by;
    this.added_time = data.added_time;
    this.folder_id = data.folder_id;
    this.role = data.role;
    this.user_id = data.user_id;
  }

  static validate(data) {
    if (data.added_by !== undefined && !((data.added_by === null || typeof data.added_by === "string"))) return false;
    if (data.added_time !== undefined && !((data.added_time === null || typeof data.added_time === "string"))) return false;
    if (data.folder_id === undefined) return false;
    if (data.folder_id !== undefined && !(typeof data.folder_id === "string")) return false;
    if (data.role === undefined) return false;
    if (data.role !== undefined && !(typeof data.role === "string")) return false;
    if (data.user_id === undefined) return false;
    if (data.user_id !== undefined && !(typeof data.user_id === "string")) return false;
    return true;
  }

  toJSON() {
    return {
      added_by: this.added_by,
      added_time: this.added_time,
      folder_id: this.folder_id,
      role: this.role,
      user_id: this.user_id,
    };
  }
}

export class Source {
  constructor(data = {}) {
    this.content = data.content;
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.file_url = data.file_url;
    this.folder_id = data.folder_id;
    this.id = data.id;
    this.status = data.status ?? "draft";
    this.title = data.title;
    this.type = data.type ?? "text";
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data) {
    if (data.content === undefined) return false;
    if (data.content !== undefined && !(typeof data.content === "string")) return false;
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.file_url !== undefined && !((data.file_url === null || typeof data.file_url === "string"))) return false;
    if (data.folder_id === undefined) return false;
    if (data.folder_id !== undefined && !(typeof data.folder_id === "string")) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.status !== undefined && !(typeof data.status === "string")) return false;
    if (data.title !== undefined && !((data.title === null || typeof data.title === "string"))) return false;
    if (data.type !== undefined && !(typeof data.type === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      content: this.content,
      created_by: this.created_by,
      created_time: this.created_time,
      file_url: this.file_url,
      folder_id: this.folder_id,
      id: this.id,
      status: this.status,
      title: this.title,
      type: this.type,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

export class SourceConcept {
  constructor(data = {}) {
    this.concept_id = data.concept_id;
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.source_id = data.source_id;
  }

  static validate(data) {
    if (data.concept_id === undefined) return false;
    if (data.concept_id !== undefined && !(typeof data.concept_id === "string")) return false;
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.source_id === undefined) return false;
    if (data.source_id !== undefined && !(typeof data.source_id === "string")) return false;
    return true;
  }

  toJSON() {
    return {
      concept_id: this.concept_id,
      created_by: this.created_by,
      created_time: this.created_time,
      source_id: this.source_id,
    };
  }
}

export class SourceTopic {
  constructor(data = {}) {
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.source_id = data.source_id;
    this.topic_id = data.topic_id;
  }

  static validate(data) {
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.source_id === undefined) return false;
    if (data.source_id !== undefined && !(typeof data.source_id === "string")) return false;
    if (data.topic_id === undefined) return false;
    if (data.topic_id !== undefined && !(typeof data.topic_id === "string")) return false;
    return true;
  }

  toJSON() {
    return {
      created_by: this.created_by,
      created_time: this.created_time,
      source_id: this.source_id,
      topic_id: this.topic_id,
    };
  }
}

