// This file is auto-generated by scripts/generate_shared_models.go.
// Do not edit manually.

interface AssessmentData {
  created_by?: string | null
  created_time?: string | null
  description?: string
  expected_time_minutes?: number
  id?: string
  is_published?: boolean
  tags?: string[]
  title?: string
  type?: string
  updated_by?: string | null
  updated_time?: string | null
}

export class Assessment {
  created_by: string | null | undefined
  created_time: string | null | undefined
  description: string | undefined
  expected_time_minutes: number | undefined
  id: string | undefined
  is_published: boolean
  tags: string[]
  title: string | undefined
  type: string | undefined
  updated_by: string | null | undefined
  updated_time: string | null | undefined

  constructor(data: AssessmentData = {}) {
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.description = data.description;
    this.expected_time_minutes = data.expected_time_minutes;
    this.id = data.id;
    this.is_published = data.is_published ?? false;
    this.tags = data.tags ?? [];
    this.title = data.title;
    this.type = data.type;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data: Record<string, unknown>): boolean {
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.description !== undefined && !(typeof data.description === "string")) return false;
    if (data.expected_time_minutes === undefined) return false;
    if (data.expected_time_minutes !== undefined && !(Number.isInteger(data.expected_time_minutes))) return false;
    if (data.expected_time_minutes !== undefined && (data.expected_time_minutes as number) < 1) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.is_published !== undefined && !(typeof data.is_published === "boolean")) return false;
    if (data.tags !== undefined && !((Array.isArray(data.tags) && (data.tags as unknown[]).every((item) => typeof item === "string")))) return false;
    if (data.title === undefined) return false;
    if (data.title !== undefined && !(typeof data.title === "string")) return false;
    if (data.type === undefined) return false;
    if (data.type !== undefined && !(typeof data.type === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON(): AssessmentData {
    return {
      created_by: this.created_by,
      created_time: this.created_time,
      description: this.description,
      expected_time_minutes: this.expected_time_minutes,
      id: this.id,
      is_published: this.is_published,
      tags: this.tags,
      title: this.title,
      type: this.type,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

interface AssignmentData {
  assessment_id?: string
  assigned_at?: string
  created_by?: string | null
  created_time?: string | null
  deadline?: string
  description?: string
  feedback?: string | null
  grade?: number | null
  id?: string
  learner_id?: string
  status?: string
  submitted_at?: string | null
  title?: string
  updated_by?: string | null
  updated_time?: string | null
}

export class Assignment {
  assessment_id: string | undefined
  assigned_at: string | undefined
  created_by: string | null | undefined
  created_time: string | null | undefined
  deadline: string | undefined
  description: string | undefined
  feedback: string | null | undefined
  grade: number | null | undefined
  id: string | undefined
  learner_id: string | undefined
  status: string
  submitted_at: string | null | undefined
  title: string | undefined
  updated_by: string | null | undefined
  updated_time: string | null | undefined

  constructor(data: AssignmentData = {}) {
    this.assessment_id = data.assessment_id;
    this.assigned_at = data.assigned_at;
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.deadline = data.deadline;
    this.description = data.description;
    this.feedback = data.feedback;
    this.grade = data.grade;
    this.id = data.id;
    this.learner_id = data.learner_id;
    this.status = data.status ?? "assigned";
    this.submitted_at = data.submitted_at;
    this.title = data.title;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data: Record<string, unknown>): boolean {
    if (data.assessment_id === undefined) return false;
    if (data.assessment_id !== undefined && !(typeof data.assessment_id === "string")) return false;
    if (data.assigned_at === undefined) return false;
    if (data.assigned_at !== undefined && !(typeof data.assigned_at === "string")) return false;
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.deadline === undefined) return false;
    if (data.deadline !== undefined && !(typeof data.deadline === "string")) return false;
    if (data.description !== undefined && !(typeof data.description === "string")) return false;
    if (data.feedback !== undefined && !((data.feedback === null || typeof data.feedback === "string"))) return false;
    if (data.grade !== undefined && !((data.grade === null || typeof data.grade === "number"))) return false;
    if (data.grade !== undefined && data.grade !== null && (data.grade as number) < 0) return false;
    if (data.grade !== undefined && data.grade !== null && (data.grade as number) > 100) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.learner_id === undefined) return false;
    if (data.learner_id !== undefined && !(typeof data.learner_id === "string")) return false;
    if (data.status !== undefined && !(typeof data.status === "string")) return false;
    if (data.submitted_at !== undefined && !((data.submitted_at === null || typeof data.submitted_at === "string"))) return false;
    if (data.title === undefined) return false;
    if (data.title !== undefined && !(typeof data.title === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON(): AssignmentData {
    return {
      assessment_id: this.assessment_id,
      assigned_at: this.assigned_at,
      created_by: this.created_by,
      created_time: this.created_time,
      deadline: this.deadline,
      description: this.description,
      feedback: this.feedback,
      grade: this.grade,
      id: this.id,
      learner_id: this.learner_id,
      status: this.status,
      submitted_at: this.submitted_at,
      title: this.title,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

interface LessonData {
  created_by?: string | null
  created_time?: string | null
  description?: string
  duration_minutes?: number
  id?: string
  is_published?: boolean
  tags?: string[]
  title?: string
  updated_by?: string | null
  updated_time?: string | null
}

export class Lesson {
  created_by: string | null | undefined
  created_time: string | null | undefined
  description: string | undefined
  duration_minutes: number | undefined
  id: string | undefined
  is_published: boolean
  tags: string[]
  title: string | undefined
  updated_by: string | null | undefined
  updated_time: string | null | undefined

  constructor(data: LessonData = {}) {
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.description = data.description;
    this.duration_minutes = data.duration_minutes;
    this.id = data.id;
    this.is_published = data.is_published ?? false;
    this.tags = data.tags ?? [];
    this.title = data.title;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data: Record<string, unknown>): boolean {
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.description !== undefined && !(typeof data.description === "string")) return false;
    if (data.duration_minutes !== undefined && !(Number.isInteger(data.duration_minutes))) return false;
    if (data.duration_minutes !== undefined && (data.duration_minutes as number) < 1) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.is_published !== undefined && !(typeof data.is_published === "boolean")) return false;
    if (data.tags !== undefined && !((Array.isArray(data.tags) && (data.tags as unknown[]).every((item) => typeof item === "string")))) return false;
    if (data.title === undefined) return false;
    if (data.title !== undefined && !(typeof data.title === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON(): LessonData {
    return {
      created_by: this.created_by,
      created_time: this.created_time,
      description: this.description,
      duration_minutes: this.duration_minutes,
      id: this.id,
      is_published: this.is_published,
      tags: this.tags,
      title: this.title,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

interface SkillData {
  created_by?: string | null
  created_time?: string | null
  description?: string
  difficulty?: string
  id?: string
  status?: string
  tags?: string[]
  title?: string
  updated_by?: string | null
  updated_time?: string | null
}

export class Skill {
  created_by: string | null | undefined
  created_time: string | null | undefined
  description: string | undefined
  difficulty: string
  id: string | undefined
  status: string
  tags: string[]
  title: string | undefined
  updated_by: string | null | undefined
  updated_time: string | null | undefined

  constructor(data: SkillData = {}) {
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.description = data.description;
    this.difficulty = data.difficulty ?? "beginner";
    this.id = data.id;
    this.status = data.status ?? "draft";
    this.tags = data.tags ?? [];
    this.title = data.title;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data: Record<string, unknown>): boolean {
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.description !== undefined && !(typeof data.description === "string")) return false;
    if (data.difficulty !== undefined && !(typeof data.difficulty === "string")) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.status !== undefined && !(typeof data.status === "string")) return false;
    if (data.tags !== undefined && !((Array.isArray(data.tags) && (data.tags as unknown[]).every((item) => typeof item === "string")))) return false;
    if (data.title === undefined) return false;
    if (data.title !== undefined && !(typeof data.title === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON(): SkillData {
    return {
      created_by: this.created_by,
      created_time: this.created_time,
      description: this.description,
      difficulty: this.difficulty,
      id: this.id,
      status: this.status,
      tags: this.tags,
      title: this.title,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

export interface SkillInputData {
  description?: string
  difficulty?: string
  tags?: string[]
  title?: string
}

export class SkillInput {
  description: string
  difficulty: string
  tags: string[]
  title: string | undefined

  constructor(data: SkillInputData = {}) {
    this.description = data.description ?? "";
    this.difficulty = data.difficulty ?? "beginner";
    this.tags = data.tags ?? [];
    this.title = data.title;
  }

  static validate(data: Record<string, unknown>): boolean {
    if (data.description !== undefined && !(typeof data.description === "string")) return false;
    if (data.difficulty !== undefined && !(typeof data.difficulty === "string")) return false;
    if (data.tags !== undefined && !((Array.isArray(data.tags) && (data.tags as unknown[]).every((item) => typeof item === "string")))) return false;
    if (data.title === undefined) return false;
    if (data.title !== undefined && !(typeof data.title === "string")) return false;
    return true;
  }

  toJSON(): SkillInputData {
    return {
      description: this.description,
      difficulty: this.difficulty,
      tags: this.tags,
      title: this.title,
    };
  }
}

interface SkillLessonData {
  created_at?: string
  created_by?: string | null
  created_time?: string | null
  id?: string
  is_required?: boolean
  lesson_id?: string
  order_index?: number
  skill_id?: string
  updated_by?: string | null
  updated_time?: string | null
}

export class SkillLesson {
  created_at: string | undefined
  created_by: string | null | undefined
  created_time: string | null | undefined
  id: string | undefined
  is_required: boolean
  lesson_id: string | undefined
  order_index: number | undefined
  skill_id: string | undefined
  updated_by: string | null | undefined
  updated_time: string | null | undefined

  constructor(data: SkillLessonData = {}) {
    this.created_at = data.created_at;
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.id = data.id;
    this.is_required = data.is_required ?? true;
    this.lesson_id = data.lesson_id;
    this.order_index = data.order_index;
    this.skill_id = data.skill_id;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data: Record<string, unknown>): boolean {
    if (data.created_at !== undefined && !(typeof data.created_at === "string")) return false;
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.is_required !== undefined && !(typeof data.is_required === "boolean")) return false;
    if (data.lesson_id === undefined) return false;
    if (data.lesson_id !== undefined && !(typeof data.lesson_id === "string")) return false;
    if (data.order_index === undefined) return false;
    if (data.order_index !== undefined && !(Number.isInteger(data.order_index))) return false;
    if (data.order_index !== undefined && (data.order_index as number) < 1) return false;
    if (data.skill_id === undefined) return false;
    if (data.skill_id !== undefined && !(typeof data.skill_id === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON(): SkillLessonData {
    return {
      created_at: this.created_at,
      created_by: this.created_by,
      created_time: this.created_time,
      id: this.id,
      is_required: this.is_required,
      lesson_id: this.lesson_id,
      order_index: this.order_index,
      skill_id: this.skill_id,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

interface StudentPerformanceData {
  created_by?: string | null
  created_time?: string | null
  current_score?: number
  id?: string
  latest_history_id?: string | null
  learner_id?: string
  level_framework?: string | null
  level_value?: string | null
  measured_at?: string
  skill_id?: string
  trend?: string
  updated_at?: string
  updated_by?: string | null
  updated_time?: string | null
}

export class StudentPerformance {
  created_by: string | null | undefined
  created_time: string | null | undefined
  current_score: number | undefined
  id: string | undefined
  latest_history_id: string | null | undefined
  learner_id: string | undefined
  level_framework: string | null | undefined
  level_value: string | null | undefined
  measured_at: string | undefined
  skill_id: string | undefined
  trend: string
  updated_at: string | undefined
  updated_by: string | null | undefined
  updated_time: string | null | undefined

  constructor(data: StudentPerformanceData = {}) {
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.current_score = data.current_score;
    this.id = data.id;
    this.latest_history_id = data.latest_history_id;
    this.learner_id = data.learner_id;
    this.level_framework = data.level_framework;
    this.level_value = data.level_value;
    this.measured_at = data.measured_at;
    this.skill_id = data.skill_id;
    this.trend = data.trend ?? "stable";
    this.updated_at = data.updated_at;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data: Record<string, unknown>): boolean {
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.current_score === undefined) return false;
    if (data.current_score !== undefined && !(typeof data.current_score === "number")) return false;
    if (data.current_score !== undefined && (data.current_score as number) < 0) return false;
    if (data.current_score !== undefined && (data.current_score as number) > 100) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.latest_history_id !== undefined && !((data.latest_history_id === null || typeof data.latest_history_id === "string"))) return false;
    if (data.learner_id === undefined) return false;
    if (data.learner_id !== undefined && !(typeof data.learner_id === "string")) return false;
    if (data.level_framework !== undefined && !((data.level_framework === null || typeof data.level_framework === "string"))) return false;
    if (data.level_value !== undefined && !((data.level_value === null || typeof data.level_value === "string"))) return false;
    if (data.measured_at === undefined) return false;
    if (data.measured_at !== undefined && !(typeof data.measured_at === "string")) return false;
    if (data.skill_id === undefined) return false;
    if (data.skill_id !== undefined && !(typeof data.skill_id === "string")) return false;
    if (data.trend !== undefined && !(typeof data.trend === "string")) return false;
    if (data.updated_at === undefined) return false;
    if (data.updated_at !== undefined && !(typeof data.updated_at === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON(): StudentPerformanceData {
    return {
      created_by: this.created_by,
      created_time: this.created_time,
      current_score: this.current_score,
      id: this.id,
      latest_history_id: this.latest_history_id,
      learner_id: this.learner_id,
      level_framework: this.level_framework,
      level_value: this.level_value,
      measured_at: this.measured_at,
      skill_id: this.skill_id,
      trend: this.trend,
      updated_at: this.updated_at,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

interface StudentPerformanceSnapshotData {
  created_by?: string | null
  created_time?: string | null
  id?: string
  learner_id?: string
  level_framework?: string | null
  level_value?: string | null
  notes?: string | null
  recorded_at?: string
  score?: number
  skill_id?: string
  source?: string
  student_performance_id?: string | null
}

export class StudentPerformanceSnapshot {
  created_by: string | null | undefined
  created_time: string | null | undefined
  id: string | undefined
  learner_id: string | undefined
  level_framework: string | null | undefined
  level_value: string | null | undefined
  notes: string | null | undefined
  recorded_at: string | undefined
  score: number | undefined
  skill_id: string | undefined
  source: string
  student_performance_id: string | null | undefined

  constructor(data: StudentPerformanceSnapshotData = {}) {
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.id = data.id;
    this.learner_id = data.learner_id;
    this.level_framework = data.level_framework;
    this.level_value = data.level_value;
    this.notes = data.notes;
    this.recorded_at = data.recorded_at;
    this.score = data.score;
    this.skill_id = data.skill_id;
    this.source = data.source ?? "system";
    this.student_performance_id = data.student_performance_id;
  }

  static validate(data: Record<string, unknown>): boolean {
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.learner_id === undefined) return false;
    if (data.learner_id !== undefined && !(typeof data.learner_id === "string")) return false;
    if (data.level_framework !== undefined && !((data.level_framework === null || typeof data.level_framework === "string"))) return false;
    if (data.level_value !== undefined && !((data.level_value === null || typeof data.level_value === "string"))) return false;
    if (data.notes !== undefined && !((data.notes === null || typeof data.notes === "string"))) return false;
    if (data.recorded_at === undefined) return false;
    if (data.recorded_at !== undefined && !(typeof data.recorded_at === "string")) return false;
    if (data.score === undefined) return false;
    if (data.score !== undefined && !(typeof data.score === "number")) return false;
    if (data.score !== undefined && (data.score as number) < 0) return false;
    if (data.score !== undefined && (data.score as number) > 100) return false;
    if (data.skill_id === undefined) return false;
    if (data.skill_id !== undefined && !(typeof data.skill_id === "string")) return false;
    if (data.source !== undefined && !(typeof data.source === "string")) return false;
    if (data.student_performance_id !== undefined && !((data.student_performance_id === null || typeof data.student_performance_id === "string"))) return false;
    return true;
  }

  toJSON(): StudentPerformanceSnapshotData {
    return {
      created_by: this.created_by,
      created_time: this.created_time,
      id: this.id,
      learner_id: this.learner_id,
      level_framework: this.level_framework,
      level_value: this.level_value,
      notes: this.notes,
      recorded_at: this.recorded_at,
      score: this.score,
      skill_id: this.skill_id,
      source: this.source,
      student_performance_id: this.student_performance_id,
    };
  }
}

interface StudentPerformanceTimelineData {
  from_time?: string | null
  generated_at?: string
  id?: string
  learner_id?: string
  performance_trends?: unknown[]
  skill_id?: string | null
  snapshots?: unknown[]
  to_time?: string | null
}

export class StudentPerformanceTimeline {
  from_time: string | null | undefined
  generated_at: string | undefined
  id: string | undefined
  learner_id: string | undefined
  performance_trends: unknown[]
  skill_id: string | null | undefined
  snapshots: unknown[]
  to_time: string | null | undefined

  constructor(data: StudentPerformanceTimelineData = {}) {
    this.from_time = data.from_time;
    this.generated_at = data.generated_at;
    this.id = data.id;
    this.learner_id = data.learner_id;
    this.performance_trends = data.performance_trends ?? [];
    this.skill_id = data.skill_id;
    this.snapshots = data.snapshots ?? [];
    this.to_time = data.to_time;
  }

  static validate(data: Record<string, unknown>): boolean {
    if (data.from_time !== undefined && !((data.from_time === null || typeof data.from_time === "string"))) return false;
    if (data.generated_at === undefined) return false;
    if (data.generated_at !== undefined && !(typeof data.generated_at === "string")) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.learner_id === undefined) return false;
    if (data.learner_id !== undefined && !(typeof data.learner_id === "string")) return false;
    if (data.performance_trends !== undefined && !(Array.isArray(data.performance_trends))) return false;
    if (data.skill_id !== undefined && !((data.skill_id === null || typeof data.skill_id === "string"))) return false;
    if (data.snapshots === undefined) return false;
    if (data.snapshots !== undefined && !(Array.isArray(data.snapshots))) return false;
    if (data.to_time !== undefined && !((data.to_time === null || typeof data.to_time === "string"))) return false;
    return true;
  }

  toJSON(): StudentPerformanceTimelineData {
    return {
      from_time: this.from_time,
      generated_at: this.generated_at,
      id: this.id,
      learner_id: this.learner_id,
      performance_trends: this.performance_trends,
      skill_id: this.skill_id,
      snapshots: this.snapshots,
      to_time: this.to_time,
    };
  }
}
