// This file is auto-generated by scripts/generate_shared_models.py.
// Do not edit manually.

export class Assessment {
  constructor(data = {}) {
    this.id = data.id;
    this.title = data.title;
    this.description = data.description;
    this.type = data.type;
    this.expected_time_minutes = data.expected_time_minutes;
    this.is_published = data.is_published ?? false;
    this.tags = data.tags ?? [];
  }

  static validate(data) {
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.title === undefined) return false;
    if (data.title !== undefined && !(typeof data.title === "string")) return false;
    if (data.description !== undefined && !(typeof data.description === "string")) return false;
    if (data.type === undefined) return false;
    if (data.type !== undefined && !(typeof data.type === "string")) return false;
    if (data.expected_time_minutes === undefined) return false;
    if (data.expected_time_minutes !== undefined && !(Number.isInteger(data.expected_time_minutes))) return false;
    if (data.expected_time_minutes !== undefined && data.expected_time_minutes < 1) return false;
    if (data.is_published !== undefined && !(typeof data.is_published === "boolean")) return false;
    if (data.tags !== undefined && !((Array.isArray(data.tags) && data.tags.every((item) => typeof item === "string")))) return false;
    return true;
  }

  toJSON() {
    return {
      id: this.id,
      title: this.title,
      description: this.description,
      type: this.type,
      expected_time_minutes: this.expected_time_minutes,
      is_published: this.is_published,
      tags: this.tags,
    };
  }
}

export class Assignment {
  constructor(data = {}) {
    this.id = data.id;
    this.assessment_id = data.assessment_id;
    this.learner_id = data.learner_id;
    this.title = data.title;
    this.description = data.description;
    this.deadline = data.deadline;
    this.status = data.status ?? "assigned";
    this.assigned_at = data.assigned_at;
    this.submitted_at = data.submitted_at ?? null;
    this.grade = data.grade ?? null;
    this.feedback = data.feedback ?? null;
  }

  static validate(data) {
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.assessment_id === undefined) return false;
    if (data.assessment_id !== undefined && !(typeof data.assessment_id === "string")) return false;
    if (data.learner_id === undefined) return false;
    if (data.learner_id !== undefined && !(typeof data.learner_id === "string")) return false;
    if (data.title === undefined) return false;
    if (data.title !== undefined && !(typeof data.title === "string")) return false;
    if (data.description !== undefined && !(typeof data.description === "string")) return false;
    if (data.deadline === undefined) return false;
    if (data.deadline !== undefined && !(typeof data.deadline === "string")) return false;
    if (data.status !== undefined && !(typeof data.status === "string")) return false;
    if (data.assigned_at === undefined) return false;
    if (data.assigned_at !== undefined && !(typeof data.assigned_at === "string")) return false;
    if (data.submitted_at !== undefined && !((data.submitted_at === null || typeof data.submitted_at === "string"))) return false;
    if (data.grade !== undefined && !((data.grade === null || typeof data.grade === "number"))) return false;
    if (data.grade !== undefined && data.grade < 0) return false;
    if (data.grade !== undefined && data.grade > 100) return false;
    if (data.feedback !== undefined && !((data.feedback === null || typeof data.feedback === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      id: this.id,
      assessment_id: this.assessment_id,
      learner_id: this.learner_id,
      title: this.title,
      description: this.description,
      deadline: this.deadline,
      status: this.status,
      assigned_at: this.assigned_at,
      submitted_at: this.submitted_at,
      grade: this.grade,
      feedback: this.feedback,
    };
  }
}

export class Lesson {
  constructor(data = {}) {
    this.id = data.id;
    this.title = data.title;
    this.description = data.description;
    this.duration_minutes = data.duration_minutes;
    this.is_published = data.is_published ?? false;
    this.tags = data.tags ?? [];
  }

  static validate(data) {
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.title === undefined) return false;
    if (data.title !== undefined && !(typeof data.title === "string")) return false;
    if (data.description !== undefined && !(typeof data.description === "string")) return false;
    if (data.duration_minutes !== undefined && !(Number.isInteger(data.duration_minutes))) return false;
    if (data.duration_minutes !== undefined && data.duration_minutes < 1) return false;
    if (data.is_published !== undefined && !(typeof data.is_published === "boolean")) return false;
    if (data.tags !== undefined && !((Array.isArray(data.tags) && data.tags.every((item) => typeof item === "string")))) return false;
    return true;
  }

  toJSON() {
    return {
      id: this.id,
      title: this.title,
      description: this.description,
      duration_minutes: this.duration_minutes,
      is_published: this.is_published,
      tags: this.tags,
    };
  }
}

export class Skill {
  constructor(data = {}) {
    this.id = data.id;
    this.title = data.title;
    this.description = data.description;
    this.difficulty = data.difficulty ?? "beginner";
    this.is_published = data.is_published ?? false;
    this.tags = data.tags ?? [];
  }

  static validate(data) {
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.title === undefined) return false;
    if (data.title !== undefined && !(typeof data.title === "string")) return false;
    if (data.description !== undefined && !(typeof data.description === "string")) return false;
    if (data.difficulty !== undefined && !(typeof data.difficulty === "string")) return false;
    if (data.is_published !== undefined && !(typeof data.is_published === "boolean")) return false;
    if (data.tags !== undefined && !((Array.isArray(data.tags) && data.tags.every((item) => typeof item === "string")))) return false;
    return true;
  }

  toJSON() {
    return {
      id: this.id,
      title: this.title,
      description: this.description,
      difficulty: this.difficulty,
      is_published: this.is_published,
      tags: this.tags,
    };
  }
}

export class SkillLesson {
  constructor(data = {}) {
    this.id = data.id;
    this.skill_id = data.skill_id;
    this.lesson_id = data.lesson_id;
    this.order_index = data.order_index;
    this.is_required = data.is_required ?? true;
    this.created_at = data.created_at;
  }

  static validate(data) {
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.skill_id === undefined) return false;
    if (data.skill_id !== undefined && !(typeof data.skill_id === "string")) return false;
    if (data.lesson_id === undefined) return false;
    if (data.lesson_id !== undefined && !(typeof data.lesson_id === "string")) return false;
    if (data.order_index === undefined) return false;
    if (data.order_index !== undefined && !(Number.isInteger(data.order_index))) return false;
    if (data.order_index !== undefined && data.order_index < 1) return false;
    if (data.is_required !== undefined && !(typeof data.is_required === "boolean")) return false;
    if (data.created_at !== undefined && !(typeof data.created_at === "string")) return false;
    return true;
  }

  toJSON() {
    return {
      id: this.id,
      skill_id: this.skill_id,
      lesson_id: this.lesson_id,
      order_index: this.order_index,
      is_required: this.is_required,
      created_at: this.created_at,
    };
  }
}

export class StudentPerformance {
  constructor(data = {}) {
    this.id = data.id;
    this.learner_id = data.learner_id;
    this.skill_id = data.skill_id;
    this.latest_history_id = data.latest_history_id ?? null;
    this.current_score = data.current_score;
    this.trend = data.trend ?? "stable";
    this.measured_at = data.measured_at;
    this.updated_at = data.updated_at;
  }

  static validate(data) {
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.learner_id === undefined) return false;
    if (data.learner_id !== undefined && !(typeof data.learner_id === "string")) return false;
    if (data.skill_id === undefined) return false;
    if (data.skill_id !== undefined && !(typeof data.skill_id === "string")) return false;
    if (data.latest_history_id !== undefined && !((data.latest_history_id === null || typeof data.latest_history_id === "string"))) return false;
    if (data.current_score === undefined) return false;
    if (data.current_score !== undefined && !(typeof data.current_score === "number")) return false;
    if (data.current_score !== undefined && data.current_score < 0) return false;
    if (data.current_score !== undefined && data.current_score > 100) return false;
    if (data.trend !== undefined && !(typeof data.trend === "string")) return false;
    if (data.measured_at === undefined) return false;
    if (data.measured_at !== undefined && !(typeof data.measured_at === "string")) return false;
    if (data.updated_at === undefined) return false;
    if (data.updated_at !== undefined && !(typeof data.updated_at === "string")) return false;
    return true;
  }

  toJSON() {
    return {
      id: this.id,
      learner_id: this.learner_id,
      skill_id: this.skill_id,
      latest_history_id: this.latest_history_id,
      current_score: this.current_score,
      trend: this.trend,
      measured_at: this.measured_at,
      updated_at: this.updated_at,
    };
  }
}

export class StudentPerformanceHistory {
  constructor(data = {}) {
    this.id = data.id;
    this.student_performance_id = data.student_performance_id;
    this.learner_id = data.learner_id;
    this.skill_id = data.skill_id;
    this.score = data.score;
    this.recorded_at = data.recorded_at;
    this.source = data.source ?? "system";
    this.notes = data.notes ?? null;
  }

  static validate(data) {
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.student_performance_id === undefined) return false;
    if (data.student_performance_id !== undefined && !(typeof data.student_performance_id === "string")) return false;
    if (data.learner_id === undefined) return false;
    if (data.learner_id !== undefined && !(typeof data.learner_id === "string")) return false;
    if (data.skill_id === undefined) return false;
    if (data.skill_id !== undefined && !(typeof data.skill_id === "string")) return false;
    if (data.score === undefined) return false;
    if (data.score !== undefined && !(typeof data.score === "number")) return false;
    if (data.score !== undefined && data.score < 0) return false;
    if (data.score !== undefined && data.score > 100) return false;
    if (data.recorded_at === undefined) return false;
    if (data.recorded_at !== undefined && !(typeof data.recorded_at === "string")) return false;
    if (data.source !== undefined && !(typeof data.source === "string")) return false;
    if (data.notes !== undefined && !((data.notes === null || typeof data.notes === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      id: this.id,
      student_performance_id: this.student_performance_id,
      learner_id: this.learner_id,
      skill_id: this.skill_id,
      score: this.score,
      recorded_at: this.recorded_at,
      source: this.source,
      notes: this.notes,
    };
  }
}
