// This file is auto-generated by scripts/generate_shared_models.go.
// Do not edit manually.

export class Assessment {
  constructor(data = {}) {
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.description = data.description;
    this.expected_time_minutes = data.expected_time_minutes;
    this.id = data.id;
    this.is_published = data.is_published ?? false;
    this.tags = data.tags ?? [];
    this.title = data.title;
    this.type = data.type;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data) {
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.description !== undefined && !(typeof data.description === "string")) return false;
    if (data.expected_time_minutes === undefined) return false;
    if (data.expected_time_minutes !== undefined && !(Number.isInteger(data.expected_time_minutes))) return false;
    if (data.expected_time_minutes !== undefined && data.expected_time_minutes < 1) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.is_published !== undefined && !(typeof data.is_published === "boolean")) return false;
    if (data.tags !== undefined && !((Array.isArray(data.tags) && data.tags.every((item) => typeof item === "string")))) return false;
    if (data.title === undefined) return false;
    if (data.title !== undefined && !(typeof data.title === "string")) return false;
    if (data.type === undefined) return false;
    if (data.type !== undefined && !(typeof data.type === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      created_by: this.created_by,
      created_time: this.created_time,
      description: this.description,
      expected_time_minutes: this.expected_time_minutes,
      id: this.id,
      is_published: this.is_published,
      tags: this.tags,
      title: this.title,
      type: this.type,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

export class Assignment {
  constructor(data = {}) {
    this.assessment_id = data.assessment_id;
    this.assigned_at = data.assigned_at;
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.deadline = data.deadline;
    this.description = data.description;
    this.feedback = data.feedback;
    this.grade = data.grade;
    this.id = data.id;
    this.learner_id = data.learner_id;
    this.status = data.status ?? "assigned";
    this.submitted_at = data.submitted_at;
    this.title = data.title;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data) {
    if (data.assessment_id === undefined) return false;
    if (data.assessment_id !== undefined && !(typeof data.assessment_id === "string")) return false;
    if (data.assigned_at === undefined) return false;
    if (data.assigned_at !== undefined && !(typeof data.assigned_at === "string")) return false;
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.deadline === undefined) return false;
    if (data.deadline !== undefined && !(typeof data.deadline === "string")) return false;
    if (data.description !== undefined && !(typeof data.description === "string")) return false;
    if (data.feedback !== undefined && !((data.feedback === null || typeof data.feedback === "string"))) return false;
    if (data.grade !== undefined && !((data.grade === null || typeof data.grade === "number"))) return false;
    if (data.grade !== undefined && data.grade < 0) return false;
    if (data.grade !== undefined && data.grade > 100) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.learner_id === undefined) return false;
    if (data.learner_id !== undefined && !(typeof data.learner_id === "string")) return false;
    if (data.status !== undefined && !(typeof data.status === "string")) return false;
    if (data.submitted_at !== undefined && !((data.submitted_at === null || typeof data.submitted_at === "string"))) return false;
    if (data.title === undefined) return false;
    if (data.title !== undefined && !(typeof data.title === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      assessment_id: this.assessment_id,
      assigned_at: this.assigned_at,
      created_by: this.created_by,
      created_time: this.created_time,
      deadline: this.deadline,
      description: this.description,
      feedback: this.feedback,
      grade: this.grade,
      id: this.id,
      learner_id: this.learner_id,
      status: this.status,
      submitted_at: this.submitted_at,
      title: this.title,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

export class Lesson {
  constructor(data = {}) {
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.description = data.description;
    this.duration_minutes = data.duration_minutes;
    this.id = data.id;
    this.is_published = data.is_published ?? false;
    this.tags = data.tags ?? [];
    this.title = data.title;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data) {
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.description !== undefined && !(typeof data.description === "string")) return false;
    if (data.duration_minutes !== undefined && !(Number.isInteger(data.duration_minutes))) return false;
    if (data.duration_minutes !== undefined && data.duration_minutes < 1) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.is_published !== undefined && !(typeof data.is_published === "boolean")) return false;
    if (data.tags !== undefined && !((Array.isArray(data.tags) && data.tags.every((item) => typeof item === "string")))) return false;
    if (data.title === undefined) return false;
    if (data.title !== undefined && !(typeof data.title === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      created_by: this.created_by,
      created_time: this.created_time,
      description: this.description,
      duration_minutes: this.duration_minutes,
      id: this.id,
      is_published: this.is_published,
      tags: this.tags,
      title: this.title,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

export class Skill {
  constructor(data = {}) {
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.description = data.description;
    this.difficulty = data.difficulty ?? "beginner";
    this.id = data.id;
    this.is_published = data.is_published ?? false;
    this.tags = data.tags ?? [];
    this.title = data.title;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data) {
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.description !== undefined && !(typeof data.description === "string")) return false;
    if (data.difficulty !== undefined && !(typeof data.difficulty === "string")) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.is_published !== undefined && !(typeof data.is_published === "boolean")) return false;
    if (data.tags !== undefined && !((Array.isArray(data.tags) && data.tags.every((item) => typeof item === "string")))) return false;
    if (data.title === undefined) return false;
    if (data.title !== undefined && !(typeof data.title === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      created_by: this.created_by,
      created_time: this.created_time,
      description: this.description,
      difficulty: this.difficulty,
      id: this.id,
      is_published: this.is_published,
      tags: this.tags,
      title: this.title,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

export class SkillInput {
  constructor(data = {}) {
    this.description = data.description ?? "";
    this.difficulty = data.difficulty ?? "beginner";
    this.tags = data.tags ?? [];
    this.title = data.title;
  }

  static validate(data) {
    if (data.description !== undefined && !(typeof data.description === "string")) return false;
    if (data.difficulty !== undefined && !(typeof data.difficulty === "string")) return false;
    if (data.tags !== undefined && !((Array.isArray(data.tags) && data.tags.every((item) => typeof item === "string")))) return false;
    if (data.title === undefined) return false;
    if (data.title !== undefined && !(typeof data.title === "string")) return false;
    return true;
  }

  toJSON() {
    return {
      description: this.description,
      difficulty: this.difficulty,
      tags: this.tags,
      title: this.title,
    };
  }
}

export class SkillLesson {
  constructor(data = {}) {
    this.created_at = data.created_at;
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.id = data.id;
    this.is_required = data.is_required ?? true;
    this.lesson_id = data.lesson_id;
    this.order_index = data.order_index;
    this.skill_id = data.skill_id;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data) {
    if (data.created_at !== undefined && !(typeof data.created_at === "string")) return false;
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.is_required !== undefined && !(typeof data.is_required === "boolean")) return false;
    if (data.lesson_id === undefined) return false;
    if (data.lesson_id !== undefined && !(typeof data.lesson_id === "string")) return false;
    if (data.order_index === undefined) return false;
    if (data.order_index !== undefined && !(Number.isInteger(data.order_index))) return false;
    if (data.order_index !== undefined && data.order_index < 1) return false;
    if (data.skill_id === undefined) return false;
    if (data.skill_id !== undefined && !(typeof data.skill_id === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      created_at: this.created_at,
      created_by: this.created_by,
      created_time: this.created_time,
      id: this.id,
      is_required: this.is_required,
      lesson_id: this.lesson_id,
      order_index: this.order_index,
      skill_id: this.skill_id,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

export class StudentPerformance {
  constructor(data = {}) {
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.current_score = data.current_score;
    this.id = data.id;
    this.latest_history_id = data.latest_history_id;
    this.learner_id = data.learner_id;
    this.level_framework = data.level_framework;
    this.level_value = data.level_value;
    this.measured_at = data.measured_at;
    this.skill_id = data.skill_id;
    this.trend = data.trend ?? "stable";
    this.updated_at = data.updated_at;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data) {
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.current_score === undefined) return false;
    if (data.current_score !== undefined && !(typeof data.current_score === "number")) return false;
    if (data.current_score !== undefined && data.current_score < 0) return false;
    if (data.current_score !== undefined && data.current_score > 100) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.latest_history_id !== undefined && !((data.latest_history_id === null || typeof data.latest_history_id === "string"))) return false;
    if (data.learner_id === undefined) return false;
    if (data.learner_id !== undefined && !(typeof data.learner_id === "string")) return false;
    if (data.level_framework !== undefined && !((data.level_framework === null || typeof data.level_framework === "string"))) return false;
    if (data.level_value !== undefined && !((data.level_value === null || typeof data.level_value === "string"))) return false;
    if (data.measured_at === undefined) return false;
    if (data.measured_at !== undefined && !(typeof data.measured_at === "string")) return false;
    if (data.skill_id === undefined) return false;
    if (data.skill_id !== undefined && !(typeof data.skill_id === "string")) return false;
    if (data.trend !== undefined && !(typeof data.trend === "string")) return false;
    if (data.updated_at === undefined) return false;
    if (data.updated_at !== undefined && !(typeof data.updated_at === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      created_by: this.created_by,
      created_time: this.created_time,
      current_score: this.current_score,
      id: this.id,
      latest_history_id: this.latest_history_id,
      learner_id: this.learner_id,
      level_framework: this.level_framework,
      level_value: this.level_value,
      measured_at: this.measured_at,
      skill_id: this.skill_id,
      trend: this.trend,
      updated_at: this.updated_at,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

export class StudentPerformanceSnapshot {
  constructor(data = {}) {
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.id = data.id;
    this.learner_id = data.learner_id;
    this.level_framework = data.level_framework;
    this.level_value = data.level_value;
    this.notes = data.notes;
    this.recorded_at = data.recorded_at;
    this.score = data.score;
    this.skill_id = data.skill_id;
    this.source = data.source ?? "system";
    this.student_performance_id = data.student_performance_id;
  }

  static validate(data) {
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.learner_id === undefined) return false;
    if (data.learner_id !== undefined && !(typeof data.learner_id === "string")) return false;
    if (data.level_framework !== undefined && !((data.level_framework === null || typeof data.level_framework === "string"))) return false;
    if (data.level_value !== undefined && !((data.level_value === null || typeof data.level_value === "string"))) return false;
    if (data.notes !== undefined && !((data.notes === null || typeof data.notes === "string"))) return false;
    if (data.recorded_at === undefined) return false;
    if (data.recorded_at !== undefined && !(typeof data.recorded_at === "string")) return false;
    if (data.score === undefined) return false;
    if (data.score !== undefined && !(typeof data.score === "number")) return false;
    if (data.score !== undefined && data.score < 0) return false;
    if (data.score !== undefined && data.score > 100) return false;
    if (data.skill_id === undefined) return false;
    if (data.skill_id !== undefined && !(typeof data.skill_id === "string")) return false;
    if (data.source !== undefined && !(typeof data.source === "string")) return false;
    if (data.student_performance_id !== undefined && !((data.student_performance_id === null || typeof data.student_performance_id === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      created_by: this.created_by,
      created_time: this.created_time,
      id: this.id,
      learner_id: this.learner_id,
      level_framework: this.level_framework,
      level_value: this.level_value,
      notes: this.notes,
      recorded_at: this.recorded_at,
      score: this.score,
      skill_id: this.skill_id,
      source: this.source,
      student_performance_id: this.student_performance_id,
    };
  }
}

export class StudentPerformanceTimeline {
  constructor(data = {}) {
    this.from_time = data.from_time;
    this.generated_at = data.generated_at;
    this.id = data.id;
    this.learner_id = data.learner_id;
    this.performance_trends = data.performance_trends ?? [];
    this.skill_id = data.skill_id;
    this.snapshots = data.snapshots ?? [];
    this.to_time = data.to_time;
  }

  static validate(data) {
    if (data.from_time !== undefined && !((data.from_time === null || typeof data.from_time === "string"))) return false;
    if (data.generated_at === undefined) return false;
    if (data.generated_at !== undefined && !(typeof data.generated_at === "string")) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.learner_id === undefined) return false;
    if (data.learner_id !== undefined && !(typeof data.learner_id === "string")) return false;
    if (data.performance_trends !== undefined && !((Array.isArray(data.performance_trends) && data.performance_trends.every((item) => true)))) return false;
    if (data.skill_id !== undefined && !((data.skill_id === null || typeof data.skill_id === "string"))) return false;
    if (data.snapshots === undefined) return false;
    if (data.snapshots !== undefined && !((Array.isArray(data.snapshots) && data.snapshots.every((item) => true)))) return false;
    if (data.to_time !== undefined && !((data.to_time === null || typeof data.to_time === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      from_time: this.from_time,
      generated_at: this.generated_at,
      id: this.id,
      learner_id: this.learner_id,
      performance_trends: this.performance_trends,
      skill_id: this.skill_id,
      snapshots: this.snapshots,
      to_time: this.to_time,
    };
  }
}

