// This file is auto-generated by scripts/generate_shared_models.py.
// Do not edit manually.

export class Lesson {
  constructor(data = {}) {
    this.id = data.id;
    this.title = data.title;
    this.description = data.description;
    this.duration_minutes = data.duration_minutes;
    this.is_published = data.is_published ?? false;
    this.tags = data.tags ?? [];
  }

  static validate(data) {
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.title === undefined) return false;
    if (data.title !== undefined && !(typeof data.title === "string")) return false;
    if (data.description !== undefined && !(typeof data.description === "string")) return false;
    if (data.duration_minutes !== undefined && !(Number.isInteger(data.duration_minutes))) return false;
    if (data.duration_minutes !== undefined && data.duration_minutes < 1) return false;
    if (data.is_published !== undefined && !(typeof data.is_published === "boolean")) return false;
    if (data.tags !== undefined && !((Array.isArray(data.tags) && data.tags.every((item) => typeof item === "string")))) return false;
    return true;
  }

  toJSON() {
    return {
      id: this.id,
      title: this.title,
      description: this.description,
      duration_minutes: this.duration_minutes,
      is_published: this.is_published,
      tags: this.tags,
    };
  }
}
