// This file is auto-generated by scripts/generate_shared_models.go.
// Do not edit manually.

export class Lesson {
  constructor(data = {}) {
    this.concept_id = data.concept_id;
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.description = data.description;
    this.difficulty = data.difficulty;
    this.duration_minutes = data.duration_minutes;
    this.id = data.id;
    this.is_published = data.is_published ?? false;
    this.source_id = data.source_id;
    this.tags = data.tags ?? [];
    this.title = data.title;
    this.type = data.type ?? "lesson";
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data) {
    if (data.concept_id !== undefined && !((data.concept_id === null || typeof data.concept_id === "string"))) return false;
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.description !== undefined && !(typeof data.description === "string")) return false;
    if (data.difficulty !== undefined && !((data.difficulty === null || typeof data.difficulty === "string"))) return false;
    if (data.duration_minutes !== undefined && !(Number.isInteger(data.duration_minutes))) return false;
    if (data.duration_minutes !== undefined && data.duration_minutes < 1) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.is_published !== undefined && !(typeof data.is_published === "boolean")) return false;
    if (data.source_id !== undefined && !((data.source_id === null || typeof data.source_id === "string"))) return false;
    if (data.tags !== undefined && !((Array.isArray(data.tags) && data.tags.every((item) => typeof item === "string")))) return false;
    if (data.title === undefined) return false;
    if (data.title !== undefined && !(typeof data.title === "string")) return false;
    if (data.type !== undefined && !(typeof data.type === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      concept_id: this.concept_id,
      created_by: this.created_by,
      created_time: this.created_time,
      description: this.description,
      difficulty: this.difficulty,
      duration_minutes: this.duration_minutes,
      id: this.id,
      is_published: this.is_published,
      source_id: this.source_id,
      tags: this.tags,
      title: this.title,
      type: this.type,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

export class Skill {
  constructor(data = {}) {
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.description = data.description;
    this.difficulty = data.difficulty ?? "beginner";
    this.id = data.id;
    this.status = data.status ?? "draft";
    this.tags = data.tags ?? [];
    this.title = data.title;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data) {
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.description !== undefined && !(typeof data.description === "string")) return false;
    if (data.difficulty !== undefined && !(typeof data.difficulty === "string")) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.status !== undefined && !(typeof data.status === "string")) return false;
    if (data.tags !== undefined && !((Array.isArray(data.tags) && data.tags.every((item) => typeof item === "string")))) return false;
    if (data.title === undefined) return false;
    if (data.title !== undefined && !(typeof data.title === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      created_by: this.created_by,
      created_time: this.created_time,
      description: this.description,
      difficulty: this.difficulty,
      id: this.id,
      status: this.status,
      tags: this.tags,
      title: this.title,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

export class SkillInput {
  constructor(data = {}) {
    this.description = data.description ?? "";
    this.difficulty = data.difficulty ?? "beginner";
    this.tags = data.tags ?? [];
    this.title = data.title;
  }

  static validate(data) {
    if (data.description !== undefined && !(typeof data.description === "string")) return false;
    if (data.difficulty !== undefined && !(typeof data.difficulty === "string")) return false;
    if (data.tags !== undefined && !((Array.isArray(data.tags) && data.tags.every((item) => typeof item === "string")))) return false;
    if (data.title === undefined) return false;
    if (data.title !== undefined && !(typeof data.title === "string")) return false;
    return true;
  }

  toJSON() {
    return {
      description: this.description,
      difficulty: this.difficulty,
      tags: this.tags,
      title: this.title,
    };
  }
}

export class SkillLesson {
  constructor(data = {}) {
    this.created_at = data.created_at;
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.id = data.id;
    this.is_required = data.is_required ?? true;
    this.lesson_id = data.lesson_id;
    this.order_index = data.order_index;
    this.skill_id = data.skill_id;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data) {
    if (data.created_at !== undefined && !(typeof data.created_at === "string")) return false;
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.is_required !== undefined && !(typeof data.is_required === "boolean")) return false;
    if (data.lesson_id === undefined) return false;
    if (data.lesson_id !== undefined && !(typeof data.lesson_id === "string")) return false;
    if (data.order_index === undefined) return false;
    if (data.order_index !== undefined && !(Number.isInteger(data.order_index))) return false;
    if (data.order_index !== undefined && data.order_index < 1) return false;
    if (data.skill_id === undefined) return false;
    if (data.skill_id !== undefined && !(typeof data.skill_id === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      created_at: this.created_at,
      created_by: this.created_by,
      created_time: this.created_time,
      id: this.id,
      is_required: this.is_required,
      lesson_id: this.lesson_id,
      order_index: this.order_index,
      skill_id: this.skill_id,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

