// This file is auto-generated by scripts/generate_shared_models.go.
// Do not edit manually.

export class Concept {
  constructor(data = {}) {
    this.canonical_name = data.canonical_name;
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.description = data.description;
    this.domain = data.domain;
    this.id = data.id;
    this.tags = data.tags ?? [];
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data) {
    if (data.canonical_name === undefined) return false;
    if (data.canonical_name !== undefined && !(typeof data.canonical_name === "string")) return false;
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.description !== undefined && !((data.description === null || typeof data.description === "string"))) return false;
    if (data.domain !== undefined && !((data.domain === null || typeof data.domain === "string"))) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.tags !== undefined && !((Array.isArray(data.tags) && data.tags.every((item) => typeof item === "string")))) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      canonical_name: this.canonical_name,
      created_by: this.created_by,
      created_time: this.created_time,
      description: this.description,
      domain: this.domain,
      id: this.id,
      tags: this.tags,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

export class ConceptAlias {
  constructor(data = {}) {
    this.alias = data.alias;
    this.concept_id = data.concept_id;
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.id = data.id;
  }

  static validate(data) {
    if (data.alias === undefined) return false;
    if (data.alias !== undefined && !(typeof data.alias === "string")) return false;
    if (data.concept_id === undefined) return false;
    if (data.concept_id !== undefined && !(typeof data.concept_id === "string")) return false;
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    return true;
  }

  toJSON() {
    return {
      alias: this.alias,
      concept_id: this.concept_id,
      created_by: this.created_by,
      created_time: this.created_time,
      id: this.id,
    };
  }
}

export class ConceptRelation {
  constructor(data = {}) {
    this.concept_a_id = data.concept_a_id;
    this.concept_b_id = data.concept_b_id;
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.relation_type = data.relation_type;
  }

  static validate(data) {
    if (data.concept_a_id === undefined) return false;
    if (data.concept_a_id !== undefined && !(typeof data.concept_a_id === "string")) return false;
    if (data.concept_b_id === undefined) return false;
    if (data.concept_b_id !== undefined && !(typeof data.concept_b_id === "string")) return false;
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.relation_type === undefined) return false;
    if (data.relation_type !== undefined && !(typeof data.relation_type === "string")) return false;
    return true;
  }

  toJSON() {
    return {
      concept_a_id: this.concept_a_id,
      concept_b_id: this.concept_b_id,
      created_by: this.created_by,
      created_time: this.created_time,
      relation_type: this.relation_type,
    };
  }
}

export class Topic {
  constructor(data = {}) {
    this.concept_ids = data.concept_ids ?? [];
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.description = data.description;
    this.folder_id = data.folder_id;
    this.id = data.id;
    this.name = data.name;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data) {
    if (data.concept_ids !== undefined && !((Array.isArray(data.concept_ids) && data.concept_ids.every((item) => typeof item === "string")))) return false;
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.description !== undefined && !((data.description === null || typeof data.description === "string"))) return false;
    if (data.folder_id === undefined) return false;
    if (data.folder_id !== undefined && !(typeof data.folder_id === "string")) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.name === undefined) return false;
    if (data.name !== undefined && !(typeof data.name === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      concept_ids: this.concept_ids,
      created_by: this.created_by,
      created_time: this.created_time,
      description: this.description,
      folder_id: this.folder_id,
      id: this.id,
      name: this.name,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

