// This file is auto-generated by scripts/generate_shared_models.py.
// Do not edit manually.

export class StudentProfile {
  constructor(data = {}) {
    this.id = data.id;
    this.user_id = data.user_id;
    this.full_name = data.full_name;
    this.age = data.age;
    this.email = data.email;
    this.phone = data.phone ?? null;
    this.grade_level = data.grade_level;
    this.education_system = data.education_system ?? "US";
    this.created_at = data.created_at;
    this.updated_at = data.updated_at;
    this.created_by = data.created_by ?? null;
    this.updated_by = data.updated_by ?? null;
    this.created_time = data.created_time ?? null;
    this.updated_time = data.updated_time ?? null;
  }

  static validate(data) {
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.user_id === undefined) return false;
    if (data.user_id !== undefined && !(typeof data.user_id === "string")) return false;
    if (data.full_name === undefined) return false;
    if (data.full_name !== undefined && !(typeof data.full_name === "string")) return false;
    if (data.age === undefined) return false;
    if (data.age !== undefined && !(Number.isInteger(data.age))) return false;
    if (data.age !== undefined && data.age < 1) return false;
    if (data.age !== undefined && data.age > 120) return false;
    if (data.email === undefined) return false;
    if (data.email !== undefined && !(typeof data.email === "string")) return false;
    if (data.phone !== undefined && !((data.phone === null || typeof data.phone === "string"))) return false;
    if (data.grade_level === undefined) return false;
    if (data.grade_level !== undefined && !(Number.isInteger(data.grade_level))) return false;
    if (data.grade_level !== undefined && data.grade_level < 1) return false;
    if (data.grade_level !== undefined && data.grade_level > 13) return false;
    if (data.education_system !== undefined && !(typeof data.education_system === "string")) return false;
    if (data.created_at === undefined) return false;
    if (data.created_at !== undefined && !(typeof data.created_at === "string")) return false;
    if (data.updated_at === undefined) return false;
    if (data.updated_at !== undefined && !(typeof data.updated_at === "string")) return false;
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      id: this.id,
      user_id: this.user_id,
      full_name: this.full_name,
      age: this.age,
      email: this.email,
      phone: this.phone,
      grade_level: this.grade_level,
      education_system: this.education_system,
      created_at: this.created_at,
      updated_at: this.updated_at,
      created_by: this.created_by,
      updated_by: this.updated_by,
      created_time: this.created_time,
      updated_time: this.updated_time,
    };
  }
}
