// This file is auto-generated by scripts/generate_shared_models.go.
// Do not edit manually.

export class StudentPerformance {
  constructor(data = {}) {
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.current_score = data.current_score;
    this.id = data.id;
    this.latest_history_id = data.latest_history_id;
    this.learner_id = data.learner_id;
    this.level_framework = data.level_framework;
    this.level_value = data.level_value;
    this.measured_at = data.measured_at;
    this.skill_id = data.skill_id;
    this.trend = data.trend ?? "stable";
    this.updated_at = data.updated_at;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
  }

  static validate(data) {
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.current_score === undefined) return false;
    if (data.current_score !== undefined && !(typeof data.current_score === "number")) return false;
    if (data.current_score !== undefined && data.current_score < 0) return false;
    if (data.current_score !== undefined && data.current_score > 100) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.latest_history_id !== undefined && !((data.latest_history_id === null || typeof data.latest_history_id === "string"))) return false;
    if (data.learner_id === undefined) return false;
    if (data.learner_id !== undefined && !(typeof data.learner_id === "string")) return false;
    if (data.level_framework !== undefined && !((data.level_framework === null || typeof data.level_framework === "string"))) return false;
    if (data.level_value !== undefined && !((data.level_value === null || typeof data.level_value === "string"))) return false;
    if (data.measured_at === undefined) return false;
    if (data.measured_at !== undefined && !(typeof data.measured_at === "string")) return false;
    if (data.skill_id === undefined) return false;
    if (data.skill_id !== undefined && !(typeof data.skill_id === "string")) return false;
    if (data.trend !== undefined && !(typeof data.trend === "string")) return false;
    if (data.updated_at === undefined) return false;
    if (data.updated_at !== undefined && !(typeof data.updated_at === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      created_by: this.created_by,
      created_time: this.created_time,
      current_score: this.current_score,
      id: this.id,
      latest_history_id: this.latest_history_id,
      learner_id: this.learner_id,
      level_framework: this.level_framework,
      level_value: this.level_value,
      measured_at: this.measured_at,
      skill_id: this.skill_id,
      trend: this.trend,
      updated_at: this.updated_at,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
    };
  }
}

export class StudentPerformanceSnapshot {
  constructor(data = {}) {
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.id = data.id;
    this.learner_id = data.learner_id;
    this.level_framework = data.level_framework;
    this.level_value = data.level_value;
    this.notes = data.notes;
    this.recorded_at = data.recorded_at;
    this.score = data.score;
    this.skill_id = data.skill_id;
    this.source = data.source ?? "system";
    this.student_performance_id = data.student_performance_id;
  }

  static validate(data) {
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.learner_id === undefined) return false;
    if (data.learner_id !== undefined && !(typeof data.learner_id === "string")) return false;
    if (data.level_framework !== undefined && !((data.level_framework === null || typeof data.level_framework === "string"))) return false;
    if (data.level_value !== undefined && !((data.level_value === null || typeof data.level_value === "string"))) return false;
    if (data.notes !== undefined && !((data.notes === null || typeof data.notes === "string"))) return false;
    if (data.recorded_at === undefined) return false;
    if (data.recorded_at !== undefined && !(typeof data.recorded_at === "string")) return false;
    if (data.score === undefined) return false;
    if (data.score !== undefined && !(typeof data.score === "number")) return false;
    if (data.score !== undefined && data.score < 0) return false;
    if (data.score !== undefined && data.score > 100) return false;
    if (data.skill_id === undefined) return false;
    if (data.skill_id !== undefined && !(typeof data.skill_id === "string")) return false;
    if (data.source !== undefined && !(typeof data.source === "string")) return false;
    if (data.student_performance_id !== undefined && !((data.student_performance_id === null || typeof data.student_performance_id === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      created_by: this.created_by,
      created_time: this.created_time,
      id: this.id,
      learner_id: this.learner_id,
      level_framework: this.level_framework,
      level_value: this.level_value,
      notes: this.notes,
      recorded_at: this.recorded_at,
      score: this.score,
      skill_id: this.skill_id,
      source: this.source,
      student_performance_id: this.student_performance_id,
    };
  }
}

export class StudentPerformanceTimeline {
  constructor(data = {}) {
    this.from_time = data.from_time;
    this.generated_at = data.generated_at;
    this.id = data.id;
    this.learner_id = data.learner_id;
    this.performance_trends = data.performance_trends ?? [];
    this.skill_id = data.skill_id;
    this.snapshots = data.snapshots ?? [];
    this.to_time = data.to_time;
  }

  static validate(data) {
    if (data.from_time !== undefined && !((data.from_time === null || typeof data.from_time === "string"))) return false;
    if (data.generated_at === undefined) return false;
    if (data.generated_at !== undefined && !(typeof data.generated_at === "string")) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.learner_id === undefined) return false;
    if (data.learner_id !== undefined && !(typeof data.learner_id === "string")) return false;
    if (data.performance_trends !== undefined && !((Array.isArray(data.performance_trends) && data.performance_trends.every((item) => true)))) return false;
    if (data.skill_id !== undefined && !((data.skill_id === null || typeof data.skill_id === "string"))) return false;
    if (data.snapshots === undefined) return false;
    if (data.snapshots !== undefined && !((Array.isArray(data.snapshots) && data.snapshots.every((item) => true)))) return false;
    if (data.to_time !== undefined && !((data.to_time === null || typeof data.to_time === "string"))) return false;
    return true;
  }

  toJSON() {
    return {
      from_time: this.from_time,
      generated_at: this.generated_at,
      id: this.id,
      learner_id: this.learner_id,
      performance_trends: this.performance_trends,
      skill_id: this.skill_id,
      snapshots: this.snapshots,
      to_time: this.to_time,
    };
  }
}

export class StudentProfile {
  constructor(data = {}) {
    this.age = data.age;
    this.created_at = data.created_at;
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.education_system = data.education_system ?? "US";
    this.email = data.email;
    this.full_name = data.full_name;
    this.grade_level = data.grade_level;
    this.id = data.id;
    this.phone = data.phone;
    this.updated_at = data.updated_at;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
    this.user_id = data.user_id;
  }

  static validate(data) {
    if (data.age === undefined) return false;
    if (data.age !== undefined && !(Number.isInteger(data.age))) return false;
    if (data.age !== undefined && data.age < 1) return false;
    if (data.age !== undefined && data.age > 120) return false;
    if (data.created_at === undefined) return false;
    if (data.created_at !== undefined && !(typeof data.created_at === "string")) return false;
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.education_system !== undefined && !(typeof data.education_system === "string")) return false;
    if (data.email === undefined) return false;
    if (data.email !== undefined && !(typeof data.email === "string")) return false;
    if (data.full_name === undefined) return false;
    if (data.full_name !== undefined && !(typeof data.full_name === "string")) return false;
    if (data.grade_level === undefined) return false;
    if (data.grade_level !== undefined && !(Number.isInteger(data.grade_level))) return false;
    if (data.grade_level !== undefined && data.grade_level < 1) return false;
    if (data.grade_level !== undefined && data.grade_level > 13) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.phone !== undefined && !((data.phone === null || typeof data.phone === "string"))) return false;
    if (data.updated_at === undefined) return false;
    if (data.updated_at !== undefined && !(typeof data.updated_at === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    if (data.user_id === undefined) return false;
    if (data.user_id !== undefined && !(typeof data.user_id === "string")) return false;
    return true;
  }

  toJSON() {
    return {
      age: this.age,
      created_at: this.created_at,
      created_by: this.created_by,
      created_time: this.created_time,
      education_system: this.education_system,
      email: this.email,
      full_name: this.full_name,
      grade_level: this.grade_level,
      id: this.id,
      phone: this.phone,
      updated_at: this.updated_at,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
      user_id: this.user_id,
    };
  }
}

