// This file is auto-generated by scripts/generate_shared_models.go.
// Do not edit manually.

interface StudentProfileData {
  age?: number
  created_at?: string
  created_by?: string | null
  created_time?: string | null
  education_system?: string
  email?: string
  full_name?: string
  grade_level?: number
  id?: string
  phone?: string | null
  updated_at?: string
  updated_by?: string | null
  updated_time?: string | null
  user_id?: string
}

export class StudentProfile {
  age: number | undefined
  created_at: string | undefined
  created_by: string | null | undefined
  created_time: string | null | undefined
  education_system: string
  email: string | undefined
  full_name: string | undefined
  grade_level: number | undefined
  id: string | undefined
  phone: string | null | undefined
  updated_at: string | undefined
  updated_by: string | null | undefined
  updated_time: string | null | undefined
  user_id: string | undefined

  constructor(data: StudentProfileData = {}) {
    this.age = data.age;
    this.created_at = data.created_at;
    this.created_by = data.created_by;
    this.created_time = data.created_time;
    this.education_system = data.education_system ?? "US";
    this.email = data.email;
    this.full_name = data.full_name;
    this.grade_level = data.grade_level;
    this.id = data.id;
    this.phone = data.phone;
    this.updated_at = data.updated_at;
    this.updated_by = data.updated_by;
    this.updated_time = data.updated_time;
    this.user_id = data.user_id;
  }

  static validate(data: Record<string, unknown>): boolean {
    if (data.age === undefined) return false;
    if (data.age !== undefined && !(Number.isInteger(data.age))) return false;
    if (data.age !== undefined && (data.age as number) < 1) return false;
    if (data.age !== undefined && (data.age as number) > 120) return false;
    if (data.created_at === undefined) return false;
    if (data.created_at !== undefined && !(typeof data.created_at === "string")) return false;
    if (data.created_by !== undefined && !((data.created_by === null || typeof data.created_by === "string"))) return false;
    if (data.created_time !== undefined && !((data.created_time === null || typeof data.created_time === "string"))) return false;
    if (data.education_system !== undefined && !(typeof data.education_system === "string")) return false;
    if (data.email === undefined) return false;
    if (data.email !== undefined && !(typeof data.email === "string")) return false;
    if (data.full_name === undefined) return false;
    if (data.full_name !== undefined && !(typeof data.full_name === "string")) return false;
    if (data.grade_level === undefined) return false;
    if (data.grade_level !== undefined && !(Number.isInteger(data.grade_level))) return false;
    if (data.grade_level !== undefined && (data.grade_level as number) < 1) return false;
    if (data.grade_level !== undefined && (data.grade_level as number) > 13) return false;
    if (data.id === undefined) return false;
    if (data.id !== undefined && !(typeof data.id === "string")) return false;
    if (data.phone !== undefined && !((data.phone === null || typeof data.phone === "string"))) return false;
    if (data.updated_at === undefined) return false;
    if (data.updated_at !== undefined && !(typeof data.updated_at === "string")) return false;
    if (data.updated_by !== undefined && !((data.updated_by === null || typeof data.updated_by === "string"))) return false;
    if (data.updated_time !== undefined && !((data.updated_time === null || typeof data.updated_time === "string"))) return false;
    if (data.user_id === undefined) return false;
    if (data.user_id !== undefined && !(typeof data.user_id === "string")) return false;
    return true;
  }

  toJSON(): StudentProfileData {
    return {
      age: this.age,
      created_at: this.created_at,
      created_by: this.created_by,
      created_time: this.created_time,
      education_system: this.education_system,
      email: this.email,
      full_name: this.full_name,
      grade_level: this.grade_level,
      id: this.id,
      phone: this.phone,
      updated_at: this.updated_at,
      updated_by: this.updated_by,
      updated_time: this.updated_time,
      user_id: this.user_id,
    };
  }
}
