// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package store

type User struct {
	ID             int32  `json:"id"`
	Username       string `json:"username"`
	FullName       string `json:"full_name"`
	Role           string `json:"role"`
	HashedPassword string `json:"hashed_password"`
}
