// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package store

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserHashByUsername(ctx context.Context, username string) (string, error)
	InitUsersRoleIndex(ctx context.Context) error
	InitUsersTable(ctx context.Context) error
	InitUsersUsernameIndex(ctx context.Context) error
	UpdateUserByUsername(ctx context.Context, arg UpdateUserByUsernameParams) error
}

var _ Querier = (*Queries)(nil)
