// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package store

import (
	"context"
)

const archiveSkillByID = `-- name: ArchiveSkillByID :one
UPDATE skills
SET status = 'archived',
    updated_by = $2,
    updated_time = NOW()
WHERE id = $1
RETURNING id, title, description, difficulty, status, tags, created_by, updated_by, created_time, updated_time
`

type ArchiveSkillByIDParams struct {
	ID        string `json:"id"`
	UpdatedBy string `json:"updated_by"`
}

func (q *Queries) ArchiveSkillByID(ctx context.Context, arg ArchiveSkillByIDParams) (Skill, error) {
	row := q.db.QueryRow(ctx, archiveSkillByID, arg.ID, arg.UpdatedBy)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.Status,
		&i.Tags,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (id, title, description, difficulty, tags, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, description, difficulty, status, tags, created_by, updated_by, created_time, updated_time
`

type CreateSkillParams struct {
	ID          string   `json:"id"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Difficulty  string   `json:"difficulty"`
	Tags        []string `json:"tags"`
	CreatedBy   string   `json:"created_by"`
	UpdatedBy   string   `json:"updated_by"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Difficulty,
		arg.Tags,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.Status,
		&i.Tags,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (username, full_name, role, hashed_password)
VALUES ($1, $2, $3, $4)
`

type CreateUserParams struct {
	Username       string `json:"username"`
	FullName       string `json:"full_name"`
	Role           string `json:"role"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Username,
		arg.FullName,
		arg.Role,
		arg.HashedPassword,
	)
	return err
}

const getSkillByID = `-- name: GetSkillByID :one
SELECT id, title, description, difficulty, status, tags, created_by, updated_by, created_time, updated_time
FROM skills
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSkillByID(ctx context.Context, id string) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkillByID, id)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.Status,
		&i.Tags,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, full_name, role, hashed_password
FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Role,
		&i.HashedPassword,
	)
	return i, err
}

const getUserHashByUsername = `-- name: GetUserHashByUsername :one
SELECT hashed_password
FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserHashByUsername(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRow(ctx, getUserHashByUsername, username)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}

const initSkillsCreatedTimeIndex = `-- name: InitSkillsCreatedTimeIndex :exec
CREATE INDEX IF NOT EXISTS idx_skills_created_time ON skills (created_time DESC)
`

func (q *Queries) InitSkillsCreatedTimeIndex(ctx context.Context) error {
	_, err := q.db.Exec(ctx, initSkillsCreatedTimeIndex)
	return err
}

const initSkillsStatusState = `-- name: InitSkillsStatusState :exec
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'skills'
          AND column_name = 'is_published'
    ) THEN
        ALTER TABLE skills ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'draft';
        UPDATE skills
        SET status = CASE
            WHEN is_published THEN 'published'
            ELSE 'draft'
        END
        WHERE status IS NULL OR status = 'draft';
        ALTER TABLE skills DROP COLUMN IF EXISTS is_published;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'chk_skills_status'
          AND conrelid = 'skills'::regclass
    ) THEN
        ALTER TABLE skills
        ADD CONSTRAINT chk_skills_status CHECK (status IN ('draft', 'published', 'archived'));
    END IF;
END $$
`

func (q *Queries) InitSkillsStatusState(ctx context.Context) error {
	_, err := q.db.Exec(ctx, initSkillsStatusState)
	return err
}

const initSkillsTable = `-- name: InitSkillsTable :exec
CREATE TABLE IF NOT EXISTS skills (
    id VARCHAR(64) PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    difficulty VARCHAR(20) NOT NULL DEFAULT 'beginner',
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    tags TEXT[] NOT NULL DEFAULT '{}',
    created_by VARCHAR(64) NOT NULL,
    updated_by VARCHAR(64) NOT NULL,
    created_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_skills_difficulty CHECK (difficulty IN ('beginner', 'intermediate', 'advanced')),
    CONSTRAINT chk_skills_status CHECK (status IN ('draft', 'published', 'archived'))
)
`

func (q *Queries) InitSkillsTable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, initSkillsTable)
	return err
}

const initUsersRoleIndex = `-- name: InitUsersRoleIndex :exec
CREATE INDEX IF NOT EXISTS idx_users_role ON users (role)
`

func (q *Queries) InitUsersRoleIndex(ctx context.Context) error {
	_, err := q.db.Exec(ctx, initUsersRoleIndex)
	return err
}

const initUsersTable = `-- name: InitUsersTable :exec
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(64) UNIQUE NOT NULL,
    full_name VARCHAR(120) NOT NULL,
    role VARCHAR(20) NOT NULL,
    hashed_password VARCHAR(255) NOT NULL
)
`

func (q *Queries) InitUsersTable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, initUsersTable)
	return err
}

const initUsersUsernameIndex = `-- name: InitUsersUsernameIndex :exec
CREATE INDEX IF NOT EXISTS idx_users_username ON users (username)
`

func (q *Queries) InitUsersUsernameIndex(ctx context.Context) error {
	_, err := q.db.Exec(ctx, initUsersUsernameIndex)
	return err
}

const listSkills = `-- name: ListSkills :many
SELECT id, title, description, difficulty, status, tags, created_by, updated_by, created_time, updated_time
FROM skills
ORDER BY created_time DESC
`

func (q *Queries) ListSkills(ctx context.Context) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.Status,
			&i.Tags,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedTime,
			&i.UpdatedTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveSkillToDraftByID = `-- name: MoveSkillToDraftByID :one
UPDATE skills
SET status = 'draft',
    updated_by = $2,
    updated_time = NOW()
WHERE id = $1
RETURNING id, title, description, difficulty, status, tags, created_by, updated_by, created_time, updated_time
`

type MoveSkillToDraftByIDParams struct {
	ID        string `json:"id"`
	UpdatedBy string `json:"updated_by"`
}

func (q *Queries) MoveSkillToDraftByID(ctx context.Context, arg MoveSkillToDraftByIDParams) (Skill, error) {
	row := q.db.QueryRow(ctx, moveSkillToDraftByID, arg.ID, arg.UpdatedBy)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.Status,
		&i.Tags,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}

const publishSkillByID = `-- name: PublishSkillByID :one
UPDATE skills
SET status = 'published',
    updated_by = $2,
    updated_time = NOW()
WHERE id = $1
RETURNING id, title, description, difficulty, status, tags, created_by, updated_by, created_time, updated_time
`

type PublishSkillByIDParams struct {
	ID        string `json:"id"`
	UpdatedBy string `json:"updated_by"`
}

func (q *Queries) PublishSkillByID(ctx context.Context, arg PublishSkillByIDParams) (Skill, error) {
	row := q.db.QueryRow(ctx, publishSkillByID, arg.ID, arg.UpdatedBy)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.Status,
		&i.Tags,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}

const updateSkillByID = `-- name: UpdateSkillByID :one
UPDATE skills
SET title = $2,
    description = $3,
    difficulty = $4,
    tags = $5,
    updated_by = $6,
    updated_time = NOW()
WHERE id = $1
RETURNING id, title, description, difficulty, status, tags, created_by, updated_by, created_time, updated_time
`

type UpdateSkillByIDParams struct {
	ID          string   `json:"id"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Difficulty  string   `json:"difficulty"`
	Tags        []string `json:"tags"`
	UpdatedBy   string   `json:"updated_by"`
}

func (q *Queries) UpdateSkillByID(ctx context.Context, arg UpdateSkillByIDParams) (Skill, error) {
	row := q.db.QueryRow(ctx, updateSkillByID,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Difficulty,
		arg.Tags,
		arg.UpdatedBy,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.Status,
		&i.Tags,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}

const updateUserByUsername = `-- name: UpdateUserByUsername :exec
UPDATE users
SET full_name = $1, role = $2, hashed_password = $3
WHERE username = $4
`

type UpdateUserByUsernameParams struct {
	FullName       string `json:"full_name"`
	Role           string `json:"role"`
	HashedPassword string `json:"hashed_password"`
	Username       string `json:"username"`
}

func (q *Queries) UpdateUserByUsername(ctx context.Context, arg UpdateUserByUsernameParams) error {
	_, err := q.db.Exec(ctx, updateUserByUsername,
		arg.FullName,
		arg.Role,
		arg.HashedPassword,
		arg.Username,
	)
	return err
}
