// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package store

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (username, full_name, role, hashed_password)
VALUES ($1, $2, $3, $4)
`

type CreateUserParams struct {
	Username       string `json:"username"`
	FullName       string `json:"full_name"`
	Role           string `json:"role"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Username,
		arg.FullName,
		arg.Role,
		arg.HashedPassword,
	)
	return err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, full_name, role, hashed_password
FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Role,
		&i.HashedPassword,
	)
	return i, err
}

const getUserHashByUsername = `-- name: GetUserHashByUsername :one
SELECT hashed_password
FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserHashByUsername(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRow(ctx, getUserHashByUsername, username)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}

const initUsersRoleIndex = `-- name: InitUsersRoleIndex :exec
CREATE INDEX IF NOT EXISTS idx_users_role ON users (role)
`

func (q *Queries) InitUsersRoleIndex(ctx context.Context) error {
	_, err := q.db.Exec(ctx, initUsersRoleIndex)
	return err
}

const initUsersTable = `-- name: InitUsersTable :exec
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(64) UNIQUE NOT NULL,
    full_name VARCHAR(120) NOT NULL,
    role VARCHAR(20) NOT NULL,
    hashed_password VARCHAR(255) NOT NULL
)
`

func (q *Queries) InitUsersTable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, initUsersTable)
	return err
}

const initUsersUsernameIndex = `-- name: InitUsersUsernameIndex :exec
CREATE INDEX IF NOT EXISTS idx_users_username ON users (username)
`

func (q *Queries) InitUsersUsernameIndex(ctx context.Context) error {
	_, err := q.db.Exec(ctx, initUsersUsernameIndex)
	return err
}

const updateUserByUsername = `-- name: UpdateUserByUsername :exec
UPDATE users
SET full_name = $1, role = $2, hashed_password = $3
WHERE username = $4
`

type UpdateUserByUsernameParams struct {
	FullName       string `json:"full_name"`
	Role           string `json:"role"`
	HashedPassword string `json:"hashed_password"`
	Username       string `json:"username"`
}

func (q *Queries) UpdateUserByUsername(ctx context.Context, arg UpdateUserByUsernameParams) error {
	_, err := q.db.Exec(ctx, updateUserByUsername,
		arg.FullName,
		arg.Role,
		arg.HashedPassword,
		arg.Username,
	)
	return err
}
